### PR TITLE
Feedback/Contact Page

### PR DESCRIPTION
**Pull request by prem-k-r**
Feedback link update
and form:
image

dark mode:
image

### CODE REVIEW

**Comment by prem-k-r** [comment]
image
clicking on this `Feedback` will redirect here

**Review by itz-rj-here — APPROVED** [review]
Wow Great Work :)

**Comment by XengShi** [comment]
> Demo: https://prem-k-r.github.io/materialYouNewTab/feedback.html

Great work! You can also add your own contact information if you want to take users feedback.

**Comment by prem-k-r** [comment]
It's ok 😅

**Pull request merged**
