### PR TITLE
l10n: Update Czech translation

### PR DESCRIPTION
**Pull request by ceskyDJ**
## Description
This pull request brings some new Czech translation strings onto the scene.

## Related Issues
- Issue #195 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
missed todo hover text

**Comment by ceskyDJ** [comment]
Oh, thanks for noticing. I just didn't see it.

**Comment by ceskyDJ** [comment]
Is it OK now?

**Comment by prem-k-r** [comment]
yep, thanks.. 
just check that if hover text is not hiding partially into the screen.. it is fully visible.. then all good

**Comment by ceskyDJ** [comment]
> just check that if hover text is not hiding partially into the screen..
It looks good.

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
@XengShi probably misssed this one to merge yesterday

**Pull request merged**
