### PR TITLE
Senitize HTML In swapDropdown Method

### PR DESCRIPTION
**Pull request by princevora**
## Description
Please describe your changes and the purpose of this pull request.

## Related Issues
- I Have tried to solve the senitize issue for swapDropdown function it is resolved
## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
Sorry I wasn't clear earlier, 
image
There is no issue with funtionality.
There were two warnings in swapDropdown function related to security: Unsafe assignment to innerHTML, line 753 and 754.

**Comment by prem-k-r** [comment]
After the current changes that you have done in the PR, it should be resolved?

**Comment by princevora** [comment]
> After the current changes that you have done in the PR, it should be resolved?

It definitely should be. Can you tell me How can i validate that, i dont know the site actully.

**Comment by itz-rj-here** [comment]
> > After the current changes that you have done in the PR, it should be resolved?
> 
> It definitely should be. Can you tell me How can i validate that, i dont know the site actully.

Me too. Idk what is the site name could be ¿

**Comment by princevora** [comment]
> > > After the current changes that you have done in the PR, it should be resolved?
> > 
> > 
> > It definitely should be. Can you tell me How can i validate that, i dont know the site actully.
> 
> Me too. Idk what is the site name could be ¿

Its interface of the mozila developers page to submit addon but, i dont know the actual page

**Comment by prem-k-r** [comment]
> > After the current changes that you have done in the PR, it should be resolved?
> 
> It definitely should be. Can you tell me How can i validate that, i dont know the site actually.

Ok awesome.. 
Leave the validation, it's fine.. probably need to be registered as developer in Firefox...
XengShi can validate later

**Review by prem-k-r — APPROVED** [review]
Thanks, Great work

**Pull request merged**
