### PR TITLE
Adding search engine selection feature

### PR DESCRIPTION
**Pull request by princevora**
- Added DropDown Support With all the supported search engine In the materialYouNewTab.
- The DropDown Supports all the colors which are currently active as it has used the pre written css classes and styles.
- The Feature has short code and i have focused on clean and readable code
- The Dropdown stores the selected search engine in the local storage same as the radio button does.
- It will automatically detect and select the appropriate search engine from local storage when ever the new tab is been created.

> ###  I have Shared A few Screen Shots Of my work below.

> ### Dark theme

image

> ### Light Theme

image

> ### Brave New Tab interface

image

### CODE REVIEW

**Comment by princevora** [comment]
I hope its all okey now.

**Comment by itz-rj-here** [comment]
@prem-k-r

**Review by prem-k-r — CHANGES_REQUESTED** [review]
It's messed up bro, many older changes are deleted.
1. sync your fork's `:main` with the repo's `:main`
2. copy your main branch to create a new updated branch
3. apply the changed that you have made, dont copy all, copy portion-wise.. where changed
4. push PR

**Comment by prem-k-r** [comment]
ok, i tested your code, it's cool, really appreciate it.
here's my feedback 
1. icons are not positioned perfectly..  increase size+ center
image

2.  behind Search With is visible, left:-14px to -16px hides it.
image

3.  larger border radius to match with overall UI, and selector color maybe mainblue bg, white text, svg blue and white color swap
image

4. keyboard up/down working, but enter not working

5. maybe it will be better if mouse pointer in that area, then deselect keyboard selection (see search suggestions)
image

**Comment by prem-k-r** [comment]
But maybe wait for XengShi first if wants to change current search icon or not

**Comment by princevora** [comment]
> But maybe wait for XengShi first if wants to change current search icon or not

Okay

**Comment by princevora** [comment]
Thank you, i will look at the suggestions

**Comment by XengShi** [comment]
> Thank you, i will look at the suggestions

This is excellent work! Could you please add an option to disable the 'Search with' section? When disabled, the dropdown menu should be displayed instead.

Currently, both are functioning the same way, so it feels a bit repetitive.

**Comment by princevora** [comment]
Let me do it.

**Comment by itz-rj-here** [comment]
Idk why you are closing the pr and again reopening it instead u should use draft button. it's too annoying actually. :(

**Comment by princevora** [comment]
> Idk why you are closing the pr and again reopening it instead u should use draft button. it's too annoying actually. :(

Sorry, My Branch And repo is just messed i swear it would be last time next. Sorry for inconvenience

**Comment by prem-k-r** [comment]
> > Thank you, i will look at the suggestions
> 
> This is excellent work! Could you please add an option to disable the 'Search with' section? When disabled, the dropdown menu should be displayed instead.
> 
> Currently, both are functioning the same way, so it feels a bit repetitive.

That's a nice idea.. leave search icon as it is but when toggled off from menu, then hide serchwith and search engines ..and change icon and enable this functionality.

**Pull request closed without merging**
