### PR TITLE
More themes: Brown, Light and Dark Grey

### PR DESCRIPTION
**Pull request by prem-k-r**
image
image
image

image
image

image
image

Demo: https://prem-k-r.github.io/materialYouNewTab/

### CODE REVIEW

**Comment by prem-k-r** [comment]
later we can add 3 more dark themes
like 
image
image
image

**Comment by XengShi** [comment]
The blue one is looking ugly but the others are nice 🙂

**Comment by prem-k-r** [comment]
> The blue one is looking ugly but the others are nice 🙂

yep, need modifications, that's why not included for now

**Comment by prem-k-r** [comment]
> image image image
> 
> image image
> 
> image image
> 
> Demo: [prem-k-r.github.io/materialYouNewTab](https://prem-k-r.github.io/materialYouNewTab/)

are these ok? @XengShi

**Comment by XengShi** [comment]
Yess great specially brown and light gray

**Comment by XengShi** [comment]
I think splinting the dark theme will enhance the appearance.

**Comment by itz-rj-here** [comment]
> 
> 
> I think splinting the dark theme will enhance the appearance.

Agreed

**Comment by prem-k-r** [comment]
> 
> 
> I think splinting the dark theme will enhance the appearance.

Alright, let's plan for that once more themes are added.
Please merge this if everything else is fine.

**Comment by XengShi** [comment]
@prem-k-r  I am worrying about bookmarks thing.
It can be easily shown using ctrl+shift+B

If we implement that in extension which requires unnecessary bookmarks permissions.

**Comment by prem-k-r** [comment]
> @prem-k-r I am worrying about bookmarks thing. It can be easily shown using ctrl+shift+B
> 
> If we implement that in extension which requires unnecessary bookmarks permissions.

how should we proceed?
even if we make make custom bookmark list, it's difficult to make it like real one.

**Comment by prem-k-r** [comment]
this, mentioning reason?
https://github.com/XengShi/materialYouNewTab/discussions/222#discussioncomment-11416864

**Comment by XengShi** [comment]
I think we can simply show a message in menu page or when extension is loaded for the first time.

"Press X+Y+B to view the bookmarks"

We can detect the browser and operating system in javascript. For showing users appropriate shortcuts

**Comment by itz-rj-here** [comment]
> @prem-k-r I am worrying about bookmarks thing. It can be easily shown using ctrl+shift+B
> 
> If we implement that in extension which requires unnecessary bookmarks permissions.

Guys, I'm working on it. I need some time tho. :(

**Comment by prem-k-r** [comment]
> > @prem-k-r I am worrying about bookmarks thing. It can be easily shown using ctrl+shift+B
> > If we implement that in extension which requires unnecessary bookmarks permissions.
> 
> Guys, I'm working on it. I need some time tho. :(

let's show alert until then

**Comment by itz-rj-here** [comment]
> > > @prem-k-r I am worrying about bookmarks thing. It can be easily shown using ctrl+shift+B
> > > If we implement that in extension which requires unnecessary bookmarks permissions.
> > 
> > 
> > Guys, I'm working on it. I need some time tho. :(
> 
> let's show alert until then

It's your choice.

**Comment by itz-rj-here** [comment]
https://screenrec.com/share/B1aKzH3VFn

This is the thing i will try to implement for the bookmark.

**Comment by prem-k-r** [comment]
Thanks 😍

**Pull request merged**
