### PR TITLE
Date l10n in some languages

### PR DESCRIPTION
**Pull request by prem-k-r**
+ Localised date format for all languages
+ Disabled alert in adaptiveIconToggle
+ Simplified digital clock date code for easier to read and maintain

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]
Looks good to me.

**Comment by XengShi** [comment]
> Looks good to me.

Send SS

**Comment by itz-rj-here** [comment]
image
Disabled alert.
image
image
Localised date format for all languages. Ex: Bangla, Uzbek.

**Comment by prem-k-r** [comment]
> > Looks good to me.
> 
> Send SS

It is just display of dates in analog and digital clock according to the seleted language.

Localized version as all language don't use format like "Thu, Nov 7" (analog clock) and "7 Thu" (digital clock)

for example in Uzbek: "Pay, 7-Noyabr"
Russian: "Чт, 7 нояб." and "7 Чт"

**Pull request merged**
