### PR TITLE
Feature: Added Pinning Functionality to ToDo List

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
- Now you can pin item in the To Do List
- Pinned Items won't get reset no matter how many days pass

https://github.com/user-attachments/assets/4aa83e77-5798-42dd-b701-3ae913e2252a

## Related Discussion
- Discussion #334 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
@prem-k-r Feel free to reduce the SVG code if you can, its very big this time 🥲

**Comment by prem-k-r** [comment]
can you please rename `span` for dark theme too

**Comment by Thunder-Blaze** [comment]
oh, sure

**Comment by prem-k-r** [comment]
line 1434

**Review by prem-k-r — APPROVED** [review]
code seems fine

**Comment by XengShi** [comment]
Please don't insert svg code if its not needed. you can directly use :
```
background: url("./svgs/pinIcon.svg")no-repeat center center;
background-size: contain; 
```

**Comment by prem-k-r** [comment]
> Please don't insert svg code if its not needed. you can directly use :
> 
> ```
> background: url("./svgs/pinIcon.svg")no-repeat center center;
> background-size: contain; 
> ```

@Thunder-Blaze 
Are you changing? please let me know
since you are busy with something, I can do it

**Comment by Thunder-Blaze** [comment]
dw I am doing it
Shouldn't take much work

**Comment by prem-k-r** [comment]
ok great..
you can use these svg files.. changed slightly
https://toffeeshare.com/c/dNRxHTR8Sd

**Comment by Thunder-Blaze** [comment]
Finally Done

**Comment by Thunder-Blaze** [comment]
@prem-k-r Done, you can review

- Pinned and Pending     -> Stays as it is
- Pinned and Completed   -> Gets reset to Pending
- Unpinned and Completed -> Gets removed
- Unpinned and Pending   -> Stays as it is

**Pull request merged**
