### PR TITLE
Fixed the Flash Issue during Reload

### LINKED ISSUE #81: Two minor bugs found
- [ ] When opening a new tab with a theme that's not the default one, it'll show the default one for a few frames
- [x] When editing the text, it'll bring you to the start each second

https://github.com/user-attachments/assets/a1f4982f-bb8c-4920-aa4f-89e371597f7b

### LINKED ISSUE #112: Display glitch on tab refresh/new tab with Digital Clock Enabled
When the digital clock is enabled, occasionally, upon opening or refreshing a new tab, the analog display briefly appears for a split second. Although it happens infrequently, the visual glitch only lasts for a fraction of a second and is not a major issue.

### LINKED ISSUE #327: Flashes when opening a new tab or refreshing
Hello, thank you for creating this amazing extension! It's absolutely beautify and I really love it.

However, I encountered a problem when using this extension. When the color is set to dark, there will be some flashes on opening a new tab or refreshing. I noticed that in a very short time, the color is set to the original variant -- the blue. Then it quickly switched back to dark in maybe hundreds of milliseconds.

For users like me who uses dark mode everywhere, sudden flashes of bright color can be very abrupt and may cause damage to vision. Is it possible to fix this? Thanks in advance!

Environment:

- macOS 15.2
- Firefox Developer Edition 134.0b9 (aarch64)

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
Added a local storage item for last body background and then use that color as the color of loading screen which will result in no flashes no matter which theme you have except for the very 1st time. 

https://github.com/user-attachments/assets/19f116d5-975f-4267-b096-c1e0387fdc1b

## Related Issues
- Closes #327 
- Closes #81 
- Closes #112 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
@prem-k-r I've used an extra async script tag as the variable needs to load before the loading screen, is that alright ?

Also we can later replace the transparent image (from Wikipedia) I used with an image of smaller size

**Comment by prem-k-r** [comment]
> @prem-k-r I've used an extra async script tag as the variable needs to load before the loading screen, is that alright ?

probably.

I'm not noticing any changes though.
Still seeing the no-JS screen
image

**Comment by Thunder-Blaze** [comment]
I added a video, is it not working the same like in video for you ?

**Comment by itz-rj-here** [comment]
@Thunder-Blaze Which operating system you are using?

**Comment by itz-rj-here** [comment]
https://screenrec.com/share/9B7XGLnjte

When i fast refresh the new tab page or rapidly open so many new tab's the default "blue" theme is seen at a little time. like in 0.001 second.

**Comment by Thunder-Blaze** [comment]
I am using Windows

@itz-rj-here I think it might be because I am loading color with JS
If I don't add with JS, I can't keep multiple colors like If I keep black color as default then it will create blinking effect on lighter themes and if I keep it blue then it will create blinking effect on dark themes

I'll try to find some way to fix it ig if possible

**Comment by Thunder-Blaze** [comment]
hmm, do you think it is OS specific issue ?
It is not breaking for me on any browser
except chrome is unable to render quick becoz of a lot tabs open ig


https://github.com/user-attachments/assets/17da87ec-861d-4096-a445-13cb794fea9f

**Comment by itz-rj-here** [comment]
> hmm, do you think it is OS specific issue ? It is not breaking for me on any browser except chrome is unable to render quick becoz of a lot tabs open ig
> 
>  2024-12-18_21-29-20.mp4

Hmmm. I just reviewed it. Idk what could be the issue actually. Maybe chrome is noob on this quick rendering thingy. :)
W8 until @XengShi Reviews it. He knows better about this things than us.

**Comment by prem-k-r** [comment]
Maybe @giwih can help.. he was also suggesting something similar https://github.com/XengShi/materialYouNewTab/pull/304#issuecomment-2537218186

**Comment by giwih** [comment]
I tried running localhost/just open html, it seems to work, but when I add it as an extension it stops working, both in firefox and chrome.

**Comment by Thunder-Blaze** [comment]
Damn, thank you so much
finally found the problem thanks to you

image

**Comment by Thunder-Blaze** [comment]
@prem-k-r @itz-rj-here you can check now, I think the problem is fixed

And I had to add a new preload.js file as others had defer attribute in their including script tags which makes them load after the html page

**Comment by prem-k-r** [comment]
Code looks good.. I'll confirm after checking on my laptop

**Review by prem-k-r — APPROVED** [review]
yeah seems kind of better workaround.
Really appreciate the work

**Comment by prem-k-r** [comment]
@Thunder-Blaze please add closes #81 and closes #112 too in the PR description

**Pull request merged**
