### PR TITLE
feat: add uzbek language

### PR DESCRIPTION
**Pull request by Firdavs9512**
Add Uzbek language translation file

### CODE REVIEW

**Comment by prem-k-r** [comment]
Also can you please confirm date format in Uzbek
Full format: "Pay, 7-noyabr" 
Short format: "Pay 7"

if yes, please change month to lowercase

**Comment by Firdavs9512** [comment]
Month names should be in uppercase. The short date format should be: 7 Pay

**Comment by Firdavs9512** [comment]
Full date format: Pay, 7-Noyabr

**Comment by prem-k-r** [comment]
Okay

**Comment by ceskyDJ** [comment]
@itz-rj-here, don't forget to mension @Firdavs9512 in translation contributors list (#155).

**Comment by itz-rj-here** [comment]
> @itz-rj-here, don't forget to mention @Firdavs9512 in translation contributors list (#155).

Okayyyy 🐸🤌

**Comment by itz-rj-here** [comment]
Bruh he merged it already bruh 🗿🤌

**Pull request merged**
