### PR TITLE
clock wierd thing when switching tabs fixed

### PR DESCRIPTION
**Pull request by Minuga-RC**

### CODE REVIEW

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Keep the tab open for 2-3 mins then you will understand something

**Comment by Minuga-RC** [comment]
@itz-rj-here everything is fixed now and I added a digital clock :)

**Comment by XengShi** [comment]
Thanks, Everything looks fine!

**Comment by itz-rj-here** [comment]
Great work.

**Pull request merged**
