### PR TITLE
Better spacing of theme and language for larger menu width

### PR DESCRIPTION
**Pull request by prem-k-r**
Also WeatherAPI transliteration corrected
and added Menu width for tr and changed for pt

for tr
image
to
image

for pt
image
image
changed to 
image
image

### CODE REVIEW

**Comment by itz-rj-here** [comment]
Can you also add scrollbar for language selector too?
There are too many languages. So, I think we should add a scrollbar on the language selector.

**Comment by prem-k-r** [comment]
> Can you also add scrollbar for language selector too? There are too many languages. So, I think we should add a scrollbar on the language selector.

There is, but it only pops up when options are about to go out from desktop, not tab

**Comment by itz-rj-here** [comment]
> See #184 XengShi comment for details

I would have recommanded to add 5-6 language showup then others will be shown when going down using scroll bar. :|

**Comment by prem-k-r** [comment]
image
to 
image

**Pull request merged**
