### PR TITLE
Search Engine Selection With Dropdown 

### PR DESCRIPTION
**Pull request by princevora**
- Added DropDown Support With all the supported search engine In the materialYouNewTab.
- The DropDown Supports all the colors which are currently active as it has used the pre written css classes and styles.
- The Feature has short code and i have focused on clean and readable code
- The Dropdown stores the selected search engine in the local storage same as the radio button does.
- It will automatically detect and select the appropriate search engine from local storage when ever the new tab is been created.

> ###  I have Shared A few Screen Shots Of my work below.

> ### Dark theme

image

> ### Light Theme

image

> ### Brave New Tab interface

image

### CODE REVIEW

**Comment by prem-k-r** [comment]
Seems great from the screenshots.
Just dropdown alignment needs to be a little left.

**Comment by princevora** [comment]
> Seems great from the screenshots. Just dropdown alignment needs to be a little left.

What about this? 
`left: -14px;`

image

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
the branch has some conflict's. Needed to be resolved.

**Comment by prem-k-r** [comment]
> > Seems great from the screenshots. Just dropdown alignment needs to be a little left.
> 
> What about this? `left: -14px;`
> 
> image

try -15px, in background `Search With` div is visible

**Comment by prem-k-r** [comment]
this dropdown menu appears when click on search engine icon, right? after that can we use keyboard to move up/down to select?
I haven't tried running it in pc yet.. can't say if it good idea.. and how it is now currently.

**Comment by princevora** [comment]
I have solved the conflicts

**Comment by prem-k-r** [comment]
Bro, it got messed up. 
Maybe it's better if you sync your `main` and copy main and reapply changes there in new branch and again push PR

**Comment by princevora** [comment]
> Bro, it got messed up. Maybe it's better if you sync your `main` and copy main and reapply changes there in new branch and again push PR

Okay wait

**Comment by princevora** [comment]
wait a moment i am changin my branch

**Comment by prem-k-r** [comment]
> wait a moment i am changin my branch, i have fixed

sure bro, np. take your time

**Pull request closed without merging**
