### PR TITLE
feat: Added Wallpaper upload option

### PR DESCRIPTION
**Pull request by prem-k-r**
image

### CODE REVIEW

**Comment by XengShi** [comment]
You are faster than me 🙂

**Comment by prem-k-r** [comment]
😅

**Comment by prem-k-r** [comment]
> 
> 
> You are faster than me 🙂

JS also done?

**Comment by XengShi** [comment]
Yess almost

**Comment by prem-k-r** [comment]
@XengShi until v2.5 is ready in few days... While uploading in chrome store.. u can use versions like 2.4.1... 
Probably uploaded twice.. 
Next one v2.4.3

**Comment by prem-k-r** [comment]
Translation left to do for this... will do tomorrow.. 

Also I think we need to do something to date/greetings and usertext.. when wallpaper selected it may not be properly visible

**Comment by XengShi** [comment]
> Translation left to do for this... will do tomorrow..
> 
> Also I think we need to do something to date/greetings and usertext.. when wallpaper selected it may not be properly visible

Add a little background or shadows
image

Bro, I live in Delhi, but it detects another Delhi, showing temperature in  minus (–)  😂😂, need fix for that
if country == India && City == Delhi : 
        Change location to India (then it will automatically show temp for New Delhi)

**Comment by prem-k-r** [comment]
image
> 
> Bro, I live in Delhi, but it detects another Delhi, showing temperature in minus (–) 😂😂, need fix for that if country == India && City == Delhi : Change location to India (then it will automatically show temp for New Delhi)

Oh, just checked on weatherAPI.. it is Delhi a township in Ontario, Canada
... Can add a condition.. Will check tomorrow..

**Comment by itz-rj-here** [comment]
@prem-k-r nice one 
image

**Comment by XengShi** [comment]
You can make it something like this

**Comment by itz-rj-here** [comment]
> 
> 
> You can make it something like this

The current one is looking good. But there is one problem. When there is no inage uploaded, you can still click the remove button.

**Comment by prem-k-r** [comment]
> @prem-k-r nice one image

XengShi was also working parallelly.. see other branch.. I have used IndexedDB instead of localStorage.. So no size limit, and storing in storage instead of memory..

**Comment by prem-k-r** [comment]
> > 
> > You can make it something like this
> 
> The current one is looking good. But there is one problem. When there is no inage uploaded, you can still click the remove button.

I'll fix it

**Comment by itz-rj-here** [comment]
> > @prem-k-r nice one image
> 
> XengShi was also working parallelly.. see other branch.. I have used IndexedDB instead of localStorage.. So no size limit, and storing in storage instead of memory..

I get it.

**Comment by prem-k-r** [comment]
> 
> 
> You can make it something like this

Ok

**Comment by prem-k-r** [comment]
> 
> 
> You can make it something like this

Is this edited image or have you implemented in code?

**Comment by itz-rj-here** [comment]
> > 
> > You can make it something like this
> 
> Is this edited image or have you implemented in code?

I guess edited img...

**Comment by XengShi** [comment]
@prem-k-r  I have edited the image

**Comment by XengShi** [comment]
@prem-k-r BG Image feature is not working. I tested it on Win11, Edge, and Chrome.
I have added [accept="image/*"] in
<input type="file" id="imageUpload" accept="image/*">.
Please check the reason for this issue.

**Comment by prem-k-r** [comment]
> @prem-k-r BG Image feature is not working. I tested it on Win11, Edge, and Chrome. I have added [accept="image/*"] in . Please check the reason for this issue.

in which device it's not working.
I have checked on Win 11- chrome, edge, brave, firefox..
working fine for me- jpg, jpeg, png, svg, gif

**Comment by prem-k-r** [comment]
> lakeside-pink-sky-sunset-minimal-art-gradient-background-7680x3215-4584
> 
> I can't apply this image, and one more from my gallery....

send as zip or mail me please

**Comment by XengShi** [comment]
https://toffeeshare.com/c/yqZwY2VCSh
These images are larger in size thats why i guess

**Comment by prem-k-r** [comment]
> [toffeeshare.com/c/yqZwY2VCSh](https://toffeeshare.com/c/yqZwY2VCSh) These images are larger in size thats why i guess

yeah, you are right. larger dimension image's having this issue

**Comment by XengShi** [comment]
Something went wrong with dark theme

Before:

Screenshot From 2024-12-01 17-18-48

After:

Screenshot From 2024-12-01 17-19-12

@prem-k-r

**Comment by prem-k-r** [comment]
giveme a sec

**Comment by itz-rj-here** [comment]
> Something went wrong with dark theme
> 
> Before:
> 
> Screenshot From 2024-12-01 17-18-48
> 
> After:
> 
> Screenshot From 2024-12-01 17-19-12
> 
> @prem-k-r

🕵️‍♀️

**Comment by XengShi** [comment]
> giveme a sec

/* Placeholder InputText color*/
#userproxy {
	color: var(--textColorDark-blue);
	/* background-color: var(--whitishColor-blue); */
}

#userLoc {
	color: var(--textColorDark-blue);
	/* background-color: var(--whitishColor-blue); */
}

#userAPI {
	color: var(--textColorDark-blue);
	/* background-color: var(--whitishColor-blue); */
}

fixed!

**Comment by prem-k-r** [comment]
> > giveme a sec
> 
> /* Placeholder InputText color*/ #userproxy { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> 
> #userLoc { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> 
> #userAPI { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> 
> fixed!

Actually they are for other darker theme

**Comment by itz-rj-here** [comment]
> > > giveme a sec
> > 
> > 
> > /* Placeholder InputText color*/ #userproxy { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> > #userLoc { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> > #userAPI { color: var(--textColorDark-blue); /* background-color: var(--whitishColor-blue); */ }
> > fixed!
> 
> Actually they are for other darker theme

:)

**Pull request merged**
