### PR TITLE
Optimized Weather stuff and More

### PR DESCRIPTION
**Pull request by prem12321kumar**
- Reduced repetitive lookups of DOM elements
- Added try-catch block in ipinfo.io 
    - fetching from city instead of IP
    - fallback to auto:ip if fetching fails.
    - show fetched location in menu
- Repositioned weather icon
- Changed display of ° to °C or °F for temperature
- Fix: Menu close button's transition for longer text translated language(Hindi and Bengali)
- Changed order of AI tools shortcuts in menu
- Added toggle to show/hide UserTextBox 
- Added toggle to show/hide Greeting in digital clock mode
- Changed some English texts and added translations in Hindi and Bengali based on what I felt was appropriate

### CODE REVIEW

**Comment by prem12321kumar** [comment]
Squash commits please
(Squash and Merge)

**Comment by prem12321kumar** [comment]
#122

**Comment by itz-rj-here** [comment]
image
Looks good great work

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
Change the manifest newtab version to 2.3 too, as you made so many changes.

**Comment by itz-rj-here** [comment]
Also can you download the weather icons and make it work when the weather icon doesn't loads?

**Comment by prem12321kumar** [comment]
Ok I'll try to do tomorrow

**Pull request merged**
