### PR TITLE
Creating Fresh PR: Manual Location + Translation

### PR DESCRIPTION
**Pull request by prem12321kumar**
+ Translated newly added options of Digital clock element in menu

- Added an option to input the location manually.
- Customized date displayed formatting in Hindi: Show full name for month and truncated week days.
- Added missing translations of almost all of the interface elements to English and provided corresponding Hindi translations.
- Mapping of week day in hindi. (It was Sun-Sat in English but corresponding in Hindi was Mon-Sun, so was showing wrong day(current week day+1) in Hindi)

### CODE REVIEW

**Comment by prem12321kumar** [comment]
Please review and merge, Thanks.

**Comment by XengShi** [comment]
Okay!

**Review by Minuga-RC — APPROVED** [review]
All looks good to me

**Comment by prem12321kumar** [comment]
Added Bangla translation.
I'm done

**Review by itz-rj-here — APPROVED** [review]
Great work @prem12321kumar. just what we needed. Thanks for your hard work.
@XengShi you can merge this too. Its good to go.

**Comment by ceskyDJ** [comment]
Nice! I'll look at it, when I have a little time.

**Comment by itz-rj-here** [comment]
Is it possible to edit the numbers too?
like it doesn't look good when changing the language to other but the number remains english.

**Comment by itz-rj-here** [comment]
I just want to know if it is?..

**Comment by ceskyDJ** [comment]
> Is it possible to edit the numbers too?

What numbers do you mean?

**Comment by itz-rj-here** [comment]
> > Is it possible to edit the numbers too?
> 
> What numbers do you mean?

The weather degrees and the digital clock time and the date numbers.

**Comment by prem12321kumar** [comment]
It should be, let me try

**Comment by itz-rj-here** [comment]
> It should be, let me try

Yeah try. Until I make the new release notes.

**Comment by prem12321kumar** [comment]
Can check later. Letting current pr merge for now.

image
Temperature messed up.

**Comment by itz-rj-here** [comment]
> Can check later. Letting current pr merge for now.
> 
> image Temperature messed up.

Just try, don't already merge it. If you make it then add it to the pr.

**Comment by XengShi** [comment]
Unfortunately getting some conflicts, Could you please resolve it.

**Comment by itz-rj-here** [comment]
@prem12321kumar

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Resolve the conflicts.

**Comment by XengShi** [comment]
I checked your repo, and you've done an excellent job! I have a few suggestions for you:

You changed 'यहाँ अपना टेक्स्ट लिखें' to 'संपादित करने के लिए दो बार टैप करें.' While your translation is more accurate for 'Double tap to Edit,' I believe 'यहाँ अपना टेक्स्ट लिखें' is simpler and easier for users to understand, and it's also shorter, like 'Double tap to Edit.'

For the Enter button, you changed it to 'दर्ज करें,' which is indeed the correct translation of 'Enter,' but in my opinion, 'सर्च करें' would be more appropriate in Hindi.

Bugs: After switching to other languages like Chinese, Russian, and Portuguese, we are seeing 'undefined' translations.

**Comment by prem12321kumar** [comment]
Thanks.
let me make suggested change:
You changed 'यहाँ अपना टेक्स्ट लिखें' to 'संपादित करने के लिए दो बार टैप करें.' While your translation is more accurate for 'Double tap to Edit,' I believe 'यहाँ अपना टेक्स्ट लिखें' is simpler and easier for users to understand, and it's also shorter, like 'Double tap to Edit.'
For the Enter button, you changed it to 'दर्ज करें,' which is indeed the correct translation of 'Enter,' but in my opinion, 'सर्च करें' would be more appropriate in Hindi.

as for the Bugs: After switching to other languages like Chinese, Russian, and Portuguese, we are seeing 'undefined' translations.
this is due to translation not provided. it will show fine after translation. i'll do MTL for it

I was not free, i'll do by an hour or so and confirm you same

**Comment by itz-rj-here** [comment]
@XengShi

**Review by itz-rj-here — APPROVED** [review]
Great.

**Comment by XengShi** [comment]
@prem12321kumar 
"....is due to translation not provided. it will show fine after translation. i'll do MTL for it...."


If translation is not provided simply use default 'English' just like the previous version.

**Comment by itz-rj-here** [comment]
What happend?

**Comment by prem12321kumar** [comment]
Earlier English was showing when was it was not defined in any other language and methods were not defined for it. 
give me few minutes, I am editing.
for any new untranslated element defined in future it will show in English, unless define in any other lang

**Comment by prem12321kumar** [comment]
@XengShi Done, Please check

**Comment by prem12321kumar** [comment]
Verified on my end

**Comment by prem12321kumar** [comment]
@ceskyDJ you can verify Czech translation now

**Comment by ceskyDJ** [comment]
> @ceskyDJ you can verify Czech translation now

Nice! Thanks for notifying me.

**Pull request merged**
