### PR TITLE
Title: Fix UI Scaling and Transition Effects

### PR DESCRIPTION
**Pull request by SupriyoOG**
### Description:

1. Changed the scaling effect to apply only to the **Google Content SVG** instead of the entire div.
2. Made the background transition for the **Google Item Div** for a subtle feel.
3. Applied the same subtle **background transition effect** to AI `a` tags for consistency.

https://github.com/user-attachments/assets/21c1508c-ce03-4fa2-bb38-cf592229f480

these are some simple changes yet good looking ;)

### CODE REVIEW

**Comment by SupriyoOG** [comment]
**IF** anybody has any objection or suggestions, please tell me!!!!!

**Comment by prem-k-r** [comment]
> **IF** anybody has any objection or suggestions, please tell me!!!!!

#246 please check comment

**Comment by itz-rj-here** [comment]
@SupriyoOG After you make any changes to the repo, you should include a video or a screenshot of the changes you did. So that we can properly understand what changes you are on doing.

**Comment by SupriyoOG** [comment]
> 

Done! anything else?

**Comment by SupriyoOG** [comment]
> @SupriyoOG After you make any changes to the repo, you should include a video or a screenshot of the changes you did. So that we can properly understand what changes you are on doing.

Done! anything else?

**Comment by itz-rj-here** [comment]
> ### Description:
> 1. Changed the scaling effect to apply only to the **Google Content SVG** instead of the entire div.
> 2. Made the background transition for the **Google Item Div** for a subtle feel.
> 3. Applied the same subtle **background transition effect** to AI `a` tags for consistency.
> 
>  Changes.mp4 
> these are some simple changes yet good looking ;)

Looks good. @XengShi

**Comment by itz-rj-here** [comment]
https://screenrec.com/share/OvYa8NRmVi

It's ok for now. Thanks for the changes...

**Review by itz-rj-here — APPROVED** [review]

**Review by itz-rj-here — APPROVED** [review]

**Comment by prem-k-r** [comment]
> [screenrec.com/share/OvYa8NRmVi](https://screenrec.com/share/OvYa8NRmVi)
> 
> It's ok for now. Thanks for the changes...

his single attribute per line is on, html code lines just got double 
AI-Tools transition effect looks awesome, but no bg shortcuts personally I dont like it and with custom wallpaper it may not be properly visible.. maybe apply similar effect removing bg box.
and there seems some issue for multi line google apps

**Comment by itz-rj-here** [comment]
> > [screenrec.com/share/OvYa8NRmVi](https://screenrec.com/share/OvYa8NRmVi)
> > It's ok for now. Thanks for the changes...
> 
> his single attribute per line is on, html code lines just got double AI-Tools transition effect looks awesome, but no bg shortcuts personally I dont like it and with custom wallpaper it may not be properly visible.. maybe apply similar effect removing bg box. and there seems some issue for multi line google apps

Actually, he coded like thousand of codes which is taking me to load. So i just saw the changes if it happens anything wrong or something. but found everything normal so i left it ok :)

**Comment by SupriyoOG** [comment]
> > [screenrec.com/share/OvYa8NRmVi](https://screenrec.com/share/OvYa8NRmVi)
> > It's ok for now. Thanks for the changes...
> 
> his single attribute per line is on, html code lines just got double AI-Tools transition effect looks awesome, but no bg shortcuts personally I dont like it and with custom wallpaper it may not be properly visible.. maybe apply similar effect removing bg box. and there seems some issue for multi line google apps

it was off, the attribute per line, idk whats seems to be the issue, if it gets fixed you can go ahead

**Comment by SupriyoOG** [comment]
when i did `ctrl + s` my prettier went from 8 tabs to 2 tabs (spacing) is that what you seem a problem? you can help me fix it

**Pull request closed without merging**
