### PR TITLE
add option for enabling background images (image for each theme) can …

### PR DESCRIPTION
**Pull request by M-416U**
…be changed in script.js in themes array

### CODE REVIEW

**Review by WhitePoodleMoth — CHANGES_REQUESTED** [review]
You should keep readme with zip files

**Comment by M-416U** [comment]
> You should keep readme with zip files

It exists within dev branch

**Review by M-416U — COMMENTED** [review]
Review

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Needed to resolve the conflicts.

**Comment by itz-rj-here** [comment]
@M-416U

**Pull request closed without merging**
