### PR TITLE
Created CODE_OF_CONDUCT.md, and some minor changes

### PR DESCRIPTION
**Pull request by prem-k-r**
Edited version in manifest to v2.4

### CODE REVIEW

**Comment by prem-k-r** [comment]
IMG_20241113_123843

**Review by itz-rj-here — APPROVED** [review]
You're doing great. Can we get security policy too?

**Comment by prem-k-r** [comment]
> You're doing great. Can we get security policy too?

There maybe security vulnerabilities in codes. Some data like weatherAPI key is not encrypted. 
A cyber security expert can tell more.

**Comment by itz-rj-here** [comment]
Hmm :|

**Review by itz-rj-here — APPROVED** [review]

**Comment by XengShi** [comment]
ummmmmmmmmmmmmm

**Comment by prem-k-r** [comment]
> ummmmmmmmmmmmmm

❔

**Comment by XengShi** [comment]
> > ummmmmmmmmmmmmm
> 
> ❔

I am afraid of this kind of thing 

"Instances of abusive, harassing, or otherwise unacceptable behavior may be 
 reported to the community leaders responsible for enforcement at 
 xengshi@duck.com. 
 All complaints will be reviewed and investigated promptly and fairly."

Like taking responsibility

**Comment by prem-k-r** [comment]
> > > ummmmmmmmmmmmmm
> > 
> > 
> > ❔
> 
> I am afraid of this kind of thing
> 
> "Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [xengshi@duck.com](mailto:xengshi@duck.com). All complaints will be reviewed and investigated promptly and fairly."
> 
> Like taking responsibility

It’s just about giving a warning if someone reports something serious,
and that’s pretty unlikely to happen.

**Comment by prem-k-r** [comment]
> > I am afraid of this kind of thing
> > "Instances of abusive, harassing, or otherwise unacceptable behavior may be reported to the community leaders responsible for enforcement at [xengshi@duck.com](mailto:xengshi@duck.com). All complaints will be reviewed and investigated promptly and fairly."
> > Like taking responsibility
> 
> It’s just about giving a warning if someone reports something serious, and that’s pretty unlikely to happen.

Changed mail to [support@github.com](mailto:support@github.com) 😂

**Comment by prem-k-r** [comment]
@XengShi, could you please merge this PR along with the Indonesian translation PR and proceed with the v2.4 release?

**Pull request merged**
