### PR TITLE
Support HTTP for URL in Shortcuts and Offline Favicon

### PR DESCRIPTION
**Pull request by prem-k-r**
http support

and image loading error on offline scenario
image
to
image

### CODE REVIEW

**Comment by XengShi** [comment]
SHould I merge it now?

**Comment by prem-k-r** [comment]
yes, thanks

**Comment by itz-rj-here** [comment]
> SHould I merge it now?

Yup.

**Review by itz-rj-here — APPROVED** [review]

**Comment by prem-k-r** [comment]
changed svg
image
to
image

**Pull request merged**
