### PR TITLE
Fix: Updated Default Key and IP Provider

### PR DESCRIPTION
**Pull request by jainam-panchal**

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]
Perfect, Working like a charm.

**Comment by XengShi** [comment]
Thanks for your efforts, but for some reasons I am getting error

New Tab - Google Chrome 09-10-2024 17_18_33

**Comment by KalinduGunathilake** [comment]
Ahh he has forgotten, but its discussed in the Issue #36. ipapi.co/json endpoint is responded with 403, so use https://ipinfo.io/json/ as the geolocation url

**Comment by jainam-panchal** [comment]
Hey!

I checked from my end. It's working as expected. 

@XengShi 
I have changed the IP Provider to https://ipinfo.io/json/
Your ss shows https://ipapi.co/json/

**Comment by KalinduGunathilake** [comment]
Just out of curiosity. Why isn't this being merged?

**Comment by itz-rj-here** [comment]
@XengShi is kinda busy. As i know. He comes here in his free time and @XengShi you need to change the ip provider. The ip provider you are using is not working for anyone. It will work after you change your ip Provider.

**Pull request merged**
