### PR TITLE
Changes related to Google apps

### PR DESCRIPTION
**Pull request by prem-k-r**
Closes https://github.com/XengShi/materialYouNewTab/issues/207
+ Added 2 more shortcuts
	- filled this spaced
image

after:
image
image

+ Changed icon of Gmail, Gmeet, Shopping and Maps
	- changed this 
image
	- changed bold Gmeet to this 
image
	- changed Shopping
	https://github.com/XengShi/materialYouNewTab/pull/205#issuecomment-2493780206
	- changed Maps
https://github.com/XengShi/materialYouNewTab/pull/205#issuecomment-2493892533
+ resized some icons

+ Added bg color and shifted position of nine dots
image
to
image

### CODE REVIEW

**Comment by prem-k-r** [comment]
Btw, how about adding bg too behind 9-dots?

like this or something similar:
image
image

**Comment by prem-k-r** [comment]
Changed Shopping icon too
image
to 
image

**Comment by prem-k-r** [comment]
Changed Maps
image
to
image

**Comment by itz-rj-here** [comment]
> Btw, how about adding bg too behind 9-dots?
> 
> like this or something similar:
> image
> image
> 

What does the animation look like when hovering into it?

**Comment by prem-k-r** [comment]
> > Btw, how about adding bg too behind 9-dots?
> > like this or something similar:
> > image
> 
> What does the animation look like when hovering into it?


https://github.com/user-attachments/assets/e6115d51-918b-4bac-8048-5cd105c74e0b

https://github.com/user-attachments/assets/e6115d51-918b-4bac-8048-5cd105c74e0b
I'm not sure, having mixed feeling. On hover scaling not applied yet

**Comment by itz-rj-here** [comment]
> > > Btw, how about adding bg too behind 9-dots?
> > > like this or something similar:
> > > image
> > 
> > 
> > What does the animation look like when hovering into it?
> 
>  Recording.2024-11-22.211542.mp4 
> https://github.com/user-attachments/assets/e6115d51-918b-4bac-8048-5cd105c74e0b I'm not sure, having mixed feeling, so haven't implemented. On hover, scaling haven't applied yet

add the bg with the animation it doesn't looks good without it. Or we have to revove the animation.

**Comment by prem-k-r** [comment]
> > > > Btw, how about adding bg too behind 9-dots?

>> I'm not sure, having mixed feeling, so haven't implemented. On hover, scaling haven't applied yet

> add the bg with the animation it doesn't looks good without it. Or we have to revove the animation.

https://github.com/user-attachments/assets/10c80462-c3d6-43fd-838b-49482aeaf6cc

doesn't fit perfectly either.

I just want to say that 9-dots doesn't getting along with other UI

**Comment by prem-k-r** [comment]
image
image
How about this?

**Comment by itz-rj-here** [comment]
My brain is not working 🙂
Ask @XengShi

**Comment by prem-k-r** [comment]
image
Added YTMusic

**Comment by itz-rj-here** [comment]
The YTMusic Name Doesn't looks good to me. Why you don't use the label short one and label full class and see how it looks. If it looks better than we are good to go with it.

**Comment by itz-rj-here** [comment]
@XengShi Why you don't reply to him and say that we are going to add a new option for google apps where he will find a ytmusic option on there.

**Comment by itz-rj-here** [comment]
What? How?
The Container should have placed on a fixed position. Why it's shifting?

https://screenrec.com/share/XuvkfcM7UB

**Comment by prem-k-r** [comment]
> The YTMusic Name Doesn't looks good to me. Why you don't use the label short one and label full class and see how it looks. If it looks better than we are good to go with it.

doesn't look good

https://github.com/user-attachments/assets/b8861226-857e-4639-b18c-0465ccfb42fa

**Comment by itz-rj-here** [comment]
> > The YTMusic Name Doesn't looks good to me. Why you don't use the label short one and label full class and see how it looks. If it looks better than we are good to go with it.
> 
> doesn't look good
> 
>  ytmusic.mp4

Uhh idk why its shifting on my one. Then Add one space on the name like this "YT Music"
Then leave the pr to be merged.

**Comment by itz-rj-here** [comment]
Cause it doesn't looks good to me when the name has no space.

**Comment by prem-k-r** [comment]
> > > The YTMusic Name Doesn't looks good to me. Why you don't use the label short one and label full class and see how it looks. If it looks better than we are good to go with it.
> > 
> > 
> > doesn't look good
> > ytmusic.mp4
> 
> Uhh idk why its shifting on my one. Anyways, Then Add one space on the name like this "YT Music" Then leave the pr to be merged.

probably shifting svg 1px up may solve ur shifting

**Comment by prem-k-r** [comment]
> Cause it doesn't looks good to me when the name has no space.

ok adding space

**Review by itz-rj-here — APPROVED** [review]
Good to Go

**Comment by itz-rj-here** [comment]
Closes #207

**Comment by itz-rj-here** [comment]
> Closes #207

Okay I am not be able to add the Closes message here :)

**Pull request merged**
