### PR TITLE
Some fixes (refer description)

### PR DESCRIPTION
**Pull request by prem-k-r**
Text shadow for date/usertext only when Wallpaper is selected, else not
better shadow effect
image
image

shadow effect on shortcut names too

back theme white changed
image
image

fix bug when no bg set alert pops up when clicked cancel delete confirmation

fix bug of showing confirm when automatically change wallpaper, when random wallpaper is selected

some other minor changes,

usertext little bit right shifted
image
to
image

uploadWallpaperText translation

### CODE REVIEW

**Comment by prem-k-r** [comment]
I hope there are no more issues now related to wallpaper

**Comment by prem-k-r** [comment]
Please review, thanks

**Comment by prem-k-r** [comment]
image
have to go for second line
image

**Review by itz-rj-here — APPROVED** [review]

**Comment by prem-k-r** [comment]
1. currently it is like this, border radius 26
image

2. border radius 20
image

3. border radius 16
image

4. Cant do this properly, with dynamic width change when lang change

**Comment by XengShi** [comment]
https://github.com/XengShi/materialYouNewTab/discussions/162#discussioncomment-11447712
Conflicts!!!!

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
@prem-k-r

**Comment by prem-k-r** [comment]
> [#162 (comment)](https://github.com/XengShi/materialYouNewTab/discussions/162#discussioncomment-11447712) Conflicts!!!!

Resolved

**Comment by XengShi** [comment]
image
Looking nincee

**Comment by itz-rj-here** [comment]
image
:) Really nice....

**Pull request merged**
