### PR TITLE
Firefox Scrollbar Issue Fixed

### PR DESCRIPTION
**Pull request by itz-rj-here**
That one comment issue made a big issue 🤣

### CODE REVIEW

**Comment by itz-rj-here** [comment]
@prem-k-r

**Comment by itz-rj-here** [comment]
@XengShi have a look if the issue is fixed now.

**Comment by prem-k-r** [comment]
> That one comment issue made a big issue 🤣

ah sorry, missed selection during copy-paste from my VS code to here

**Review by prem-k-r — APPROVED** [review]

**Comment by XengShi** [comment]
image

Rip rounded corners!

**Comment by prem-k-r** [comment]
> image
> 
> Rip rounded corners!

Is this chrome or Firefox?

**Comment by XengShi** [comment]
> > image
> > 
> > Rip rounded corners!
> 
> Is this chrome or Firefox? 

Firefox on windows, 
I am not getting any issues in Linux even in Firefox.

@prem-k-r Do you have Windows or Linux?

**Pull request merged**
