### PR TITLE
Changed Language icon

### PR DESCRIPTION
**Pull request by prem-k-r**
changed
image
to
image

We were using the Google Translate icon. While it looked good, it included Google's "G" logo.
Additionally, it may have given off the impression of machine translation, as it resembled the icon also used in browsers for automatic translations.

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]
Great Work @prem-k-r

**Comment by itz-rj-here** [comment]
@prem-k-r I think we should remove all the useless and extra comments from the files. Also we need to make the code look more easy to understand.

**Comment by itz-rj-here** [comment]
image

**Comment by prem-k-r** [comment]
Most of the unimportant comment have been deleted, I think.

**Comment by prem-k-r** [comment]
> image

Yeah, old Theme s property, when languages was not there.. we can remove it.. if XengShi agrees

**Comment by itz-rj-here** [comment]
> Most of the unimportant comment have been deleted, I think.

We should recheck all once more.

**Comment by itz-rj-here** [comment]
I'm trying to modify the language style.

**Comment by prem-k-r** [comment]
> > Most of the unimportant comment have been deleted, I think.
> 
> We should recheck all once more.

You'll find some in script.js, like shortcuts related functions, screen size related.. some unused declaration.. etc. we can keep it for future

**Pull request merged**
