### PR TITLE
Shortcut Editing Functionality

### PR DESCRIPTION
**Pull request by raphaelritz**
**This PR adds a new settings page, that fully respects all [m3.material.io](https://m3.material.io) guidelines, and allows for editing of the six default shortcuts, as well as adding, removing, and resetting shortcuts.**

When a shortcut with a URL that is not in the default shortcuts is added, the amazing custom icons are unfortunately not available, so the apple-touch-icon and as a fallback simply the favicon of the webpage is used as an icon.
This looks significantly less cool, of course, especially since not all webpage icons have the same shape. To counteract this I added as an experimental feature so called "adaptive icon shapes", that simply shrinks the icon such that it fits into the circle.

I have added settings such as the maximum and minimum amount of supported shortcuts as constants in the JS file, and generally did my best to respect best practices, so that it would be easy to maintain and edit in the future.

I hope you like what I made, please let me know what I should improve!
This is my first contribution to an open source project, so I apologize in advance if my code is not that good.

Kind regards,
Raphael Ritz

### CODE REVIEW

**Review by itz-rj-here — COMMENTED** [review]
Bro literally edited the whole project

**Comment by XengShi** [comment]
Thank you for your outstanding work! The animation you added when clicking shortcut icon is a lovely touch.

**Comment by XengShi** [comment]
I am **encountering** some **conflicts** and **can't merge** your pull request. Could you please clone the current repository and add your changes into it? 
I don't have much experience with the complex Git commands to solve the issue. If you have a better solution, please let me know.

**Comment by raphaelritz** [comment]
On it!

**Comment by raphaelritz** [comment]
Before I update this pull request, I wanted to know what you think of the default values? Firstly, the maximum and minimum allowed shortcuts.
Currently, they are set to minimum 1, and maximum 20 shortcuts, as I believe it allows the user a lot of freedom, without potentially causing display issues on a normal aspect ratio. However, I wanted to get your opinion on it, since this is your project, @XengShi !

Another default value where I just put something random is the placeholder that appears when you add a new shortcut:
Currently the name is set to "Placeholder", and the URL to this GitHub repo. However, there are many other options, and I was thinking "New Shortcut" could also be a viable name.
What should I set these values to before the merge?

I am looking forward to your feedback,
Kind regards

**Comment by XengShi** [comment]
.............
Currently, they are set to minimum 1, and maximum 20 shortcuts, as I believe it allows the user a lot of freedom, without potentially causing display issues on a normal aspect ratio. However, I wanted to get your opinion on it, .............

Just do what you like, if the shortcuts are so many try adding scrolling like functionality or wrap the elements to avoid the issue for smaller devices. By the way I am loving your work!

**Comment by raphaelritz** [comment]
Thank you so much for your kind words! I will just briefly add the scrolling functionality you mentioned, and add language support to all the strings I included, then this should be ready to merge.

**Comment by XengShi** [comment]
Screenshot from 2024-10-10 17-41-52

When we editing shortcuts add some kinda hint, it goes completely blank! this can be done using 'placeholder' like ->
`<div><input class="shortcutName" placeholder="Example"><input class="URL" placeholder="www.example.com"></div>`

and I guess previously there was delete button bring it back!

**Comment by raphaelritz** [comment]
When I clone the repo again, and run it, everything works as expected for me!

image

I see that also your add button and reset button at the top right are missing. Are you on the most recent commit?

**Comment by XengShi** [comment]
Hey! I tested it again on Windows, and everything works perfectly. Then I re-tested it on Linux (Manjaro) in Chrome, Brave, and Firefox, and in all of them, the options appeared to be missing. In firefox I realized they aren’t actually missing — they’re just going off-screen. I applied a negative margin-left to container, and the buttons showed up.

I understand how frustrating it can be when the same code works fine in one place but not in another. Don’t rush!! we don’t need an immediate fix. Since it's working well on Windows and not causing any serious issues on Linux, we’re in good shape for now.

Screenshot from 2024-10-10 19-21-23

**Comment by raphaelritz** [comment]
Ok, thank you for testing this out! I will work on a fix and open a new pull request as soon as everything works.

**Pull request merged**
