### PR TITLE
Small Changes

### PR DESCRIPTION
**Pull request by itz-rj-here**
Removed the icon.png file as the blue.png icon is already included and increased the size of the icon in readme file to make it looks better

### CODE REVIEW

**Comment by prem-k-r** [comment]
`icon.png` was previously used for referencing in `Readme.md`
As it's the original icon in higher quality, so perhaps we should keep it.

Personally, I prefer the smaller icon in the README file. A larger icon works best when it has more significance.

But yeah, upto @XengShi

**Comment by itz-rj-here** [comment]
> `icon.png` was previously used for referencing in `Readme.md`
> As it's the original icon in higher quality, so perhaps we should keep it.
> 
> Personally, I prefer the smaller icon in the README file. A larger icon works best when it has more significance.
> 
> But yeah, upto @XengShi 

Yup if he has different things in his mind. I will close this.

**Comment by itz-rj-here** [comment]
@XengShi Should i close this?

**Comment by XengShi** [comment]
> > `icon.png` was previously used for referencing in `Readme.md`
> > As it's the original icon in higher quality, so perhaps we should keep it.
> > 
> > Personally, I prefer the smaller icon in the README file. A larger icon works best when it has more significance.
> > 
> > But yeah, upto @XengShi 
> 
> Yup if he has different things in his mind. I will close this.

I have 'Neuralink brain chip' in my mind

**Comment by itz-rj-here** [comment]
> > > `icon.png` was previously used for referencing in `Readme.md`
> > > As it's the original icon in higher quality, so perhaps we should keep it.
> > > Personally, I prefer the smaller icon in the README file. A larger icon works best when it has more significance.
> > > But yeah, upto @XengShi
> > 
> > 
> > Yup if he has different things in his mind. I will close this.
> 
> I have 'Neuralink brain chip' in my mind

He is on Elon Mask's mind @prem-k-r . 💀

**Pull request closed without merging**
