### PR TITLE
Fixed the Proxy Disclaimer Cancel Button Issue

### LINKED ISSUE #208: Proxy is being activated even when the user clicks Cancel in the confirm() dialog
image

### PR DESCRIPTION
**Pull request by itz-rj-here**
Closes #208 
Bug Issue Fix Requested by @prem-k-r 

Information about the fix: https://screenrec.com/share/QFIG9l4W7o

### CODE REVIEW

**Comment by itz-rj-here** [comment]
@prem-k-r @XengShi Here check if the issue is fixed :)
Thank me later.

**Review by prem-k-r — CHANGES_REQUESTED** [review]
All good. just add a try-catch block for `getAutocompleteSuggestions` in 
image

**Comment by itz-rj-here** [comment]
> All good. just add a try-catch block for `getAutocompleteSuggestions` in image

Like this?
image

**Comment by prem-k-r** [comment]
yep

**Comment by itz-rj-here** [comment]
Now? @prem-k-r

**Review by prem-k-r — APPROVED** [review]
Perfect

**Comment by itz-rj-here** [comment]
@XengShi Are you still going to merge it?

**Comment by XengShi** [comment]
> @XengShi Are you still going to merge it?

What did you mean "still going to merge....." ? 
Shouldn't I merge it?

**Comment by prem-k-r** [comment]
> > @XengShi Are you still going to merge it?
> 
> What did you mean "still going to merge....." ? Shouldn't I merge it?

He was probably being sarcastic, possibly asking when the merge will happen.

**Comment by XengShi** [comment]
image

Getting an error after enabling search suggestions without turning on the proxy bypass toggle. This error was already present before.

**Comment by prem-k-r** [comment]
Yeah from catch block, when browser blocked access due to cors.

**Pull request merged**
