### PR TITLE
Fix incorrect Chinese translations

### PR DESCRIPTION
**Pull request by TIANLI0**

### CODE REVIEW

**Comment by itz-rj-here** [comment]
@Guy-Berryman @prem-k-r

**Comment by itz-rj-here** [comment]
I guess there are 2 chinese language. But still i don't get it.

**Comment by TIANLI0** [comment]
> I guess there are 2 chinese language. But still i don't get it.

Thank you for your response. The changes I made were specifically to correct the Simplified Chinese translations. The original text seemed to be machine-translated, which led to some inaccuracies and unnatural phrasing in the context of Simplified Chinese.

For example, "GitHub" was translated as "吉特哈布", but in reality, when referring to "GitHub" in a Chinese-speaking environment, we typically do not translate it; we keep it as "GitHub". Additionally, there were a few other instances where the translation did not make logical sense or was not commonly used in the target language.

I hope this clarifies the purpose of my PR. If you have any further questions or need more details, please feel free to ask.

**Review by prem-k-r — CHANGES_REQUESTED** [review]
All good, 
I've raised PR in your fork repo, please merge or apply the changes.

**Review by prem-k-r — APPROVED** [review]
Thanks

**Comment by XengShi** [comment]
Thanks for the contribution!

**Comment by prem-k-r** [comment]
@TIANLI0 can you please also confirm if date format is correct or not in both analog and digital clock.

**Comment by TIANLI0** [comment]
> @TIANLI0 can you please also confirm if date format is correct or not in both analog and digital clock.

I've double-checked the date format in both the analog and digital clock, and it appears to be correct. The formats are consistent with the standard conventions used in Simplified Chinese.

**Comment by prem-k-r** [comment]
That's great!

**Pull request merged**
