### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by deepakdeepu000**
Added the Claude AI in AI tools

### CODE REVIEW

**Comment by itz-rj-here** [comment]
Please add a screenshot of the changes

**Review by prem-k-r — CHANGES_REQUESTED** [review]
image
update svg please

**Comment by deepakdeepu000** [comment]
screenshot 1

**Comment by prem-k-r** [comment]
> screenshot 1

Browser's homepage screenshot, reflecting changes

**Comment by prem-k-r** [comment]
Website link is also incorrect.. missing colons

**Review by deepakdeepu000 — COMMENTED** [review]
Corrected the Link and also included the Svg code fo the Claude

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Still the SVG Code is wrong.

**Comment by deepakdeepu000** [comment]
Screenshot 2

**Comment by itz-rj-here** [comment]
> Screenshot 2

Yup the placement is wrong.

**Comment by itz-rj-here** [comment]
See my changes i did in your repo pls.

**Comment by prem-k-r** [comment]
wait

**Comment by prem-k-r** [comment]
image
```
<a href="https://claude.ai/">
                <div class="tIcon">
                    <svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <rect class="accentColor aiDarkIcons" height="24" rx="12" width="24" />
                        <path class="bgLightTint" style="transform: scale(0.9); transform-origin: center;"
                            d="m5.92 15.3l3.94-2.2l.06-.2l-.06-.1h-.2L9 12.76l-2.24-.06l-1.96-.1l-1.9-.1l-.48-.1l-.42-.6l.04-.3l.4-.26l.58.04l1.26.1l1.9.12l1.38.08l2.04.24h.32l.04-.14l-.1-.08l-.08-.08L7.8 10.2L5.68 8.8l-1.12-.82l-.6-.4l-.3-.4l-.12-.84l.54-.6l.74.06l.18.04l.74.58l1.6 1.22L9.4 9.2l.3.24l.12-.08l.02-.06l-.14-.22L8.6 7L7.4 4.92l-.54-.86l-.14-.52c-.06-.2-.08-.4-.08-.6l.6-.84l.36-.1l.84.12l.32.28l.52 1.2l.82 1.86l1.3 2.52l.4.76l.2.68l.06.2h.14v-.1l.1-1.44l.2-1.74l.2-2.24l.06-.64l.32-.76l.6-.4l.52.22l.4.58l-.06.36L14.32 5l-.52 2.42l-.3 1.64h.18l.2-.22l.82-1.08l1.38-1.72l.6-.7l.72-.74l.46-.36h.86l.62.94l-.28.98l-.88 1.12l-.74.94l-1.06 1.42l-.64 1.14l.06.08h.14l2.4-.52l1.28-.22l1.52-.26l.7.32l.08.32l-.28.68l-1.64.4l-1.92.4l-2.86.66l-.04.02l.04.06l1.28.12l.56.04h1.36l2.52.2l.66.4l.38.54l-.06.4l-1.02.52l-1.36-.32l-3.2-.76l-1.08-.26h-.16v.08l.92.9l1.66 1.5l2.12 1.94l.1.48l-.26.4l-.28-.04l-1.84-1.4l-.72-.6l-1.6-1.36h-.1v.14l.36.54l1.96 2.94l.1.9l-.14.28l-.52.2l-.54-.12l-1.16-1.6l-1.2-1.8l-.94-1.64l-.1.08l-.58 6.04l-.26.3l-.6.24l-.5-.4l-.28-.6l.28-1.24l.32-1.6l.26-1.28l.24-1.58l.14-.52v-.04h-.14l-1.2 1.66l-1.8 2.46l-1.44 1.52l-.34.14l-.6-.3l.06-.56l.32-.46l2-2.56l1.2-1.58l.8-.92l-.02-.1h-.06l-5.28 3.44l-.94.12l-.4-.4l.04-.6l.2-.2l1.6-1.1z" />
                    </svg>
                </div>
                <div class="tLabel" id="claude">Claude</div>
            </a>
 ```

**Comment by itz-rj-here** [comment]
> use this
> 
> ```
> <a href="https://claude.ai/new/">
>                 <div class="tIcon">
>                     <svg width="26" height="26" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
>                         <rect class="accentColor aiDarkIcons" height="100%" rx="50%" width="100%" />
>                         <path class="bgLightTint" style="transform: scale(0.85); transform-origin: center;"
>                             d="m5.92 15.3l3.94-2.2l.06-.2l-.06-.1h-.2L9 12.76l-2.24-.06l-1.96-.1l-1.9-.1l-.48-.1l-.42-.6l.04-.3l.4-.26l.58.04l1.26.1l1.9.12l1.38.08l2.04.24h.32l.04-.14l-.1-.08l-.08-.08L7.8 10.2L5.68 8.8l-1.12-.82l-.6-.4l-.3-.4l-.12-.84l.54-.6l.74.06l.18.04l.74.58l1.6 1.22L9.4 9.2l.3.24l.12-.08l.02-.06l-.14-.22L8.6 7L7.4 4.92l-.54-.86l-.14-.52c-.06-.2-.08-.4-.08-.6l.6-.84l.36-.1l.84.12l.32.28l.52 1.2l.82 1.86l1.3 2.52l.4.76l.2.68l.06.2h.14v-.1l.1-1.44l.2-1.74l.2-2.24l.06-.64l.32-.76l.6-.4l.52.22l.4.58l-.06.36L14.32 5l-.52 2.42l-.3 1.64h.18l.2-.22l.82-1.08l1.38-1.72l.6-.7l.72-.74l.46-.36h.86l.62.94l-.28.98l-.88 1.12l-.74.94l-1.06 1.42l-.64 1.14l.06.08h.14l2.4-.52l1.28-.22l1.52-.26l.7.32l.08.32l-.28.68l-1.64.4l-1.92.4l-2.86.66l-.04.02l.04.06l1.28.12l.56.04h1.36l2.52.2l.66.4l.38.54l-.06.4l-1.02.52l-1.36-.32l-3.2-.76l-1.08-.26h-.16v.08l.92.9l1.66 1.5l2.12 1.94l.1.48l-.26.4l-.28-.04l-1.84-1.4l-.72-.6l-1.6-1.36h-.1v.14l.36.54l1.96 2.94l.1.9l-.14.28l-.52.2l-.54-.12l-1.16-1.6l-1.2-1.8l-.94-1.64l-.1.08l-.58 6.04l-.26.3l-.6.24l-.5-.4l-.28-.6l.28-1.24l.32-1.6l.26-1.28l.24-1.58l.14-.52v-.04h-.14l-1.2 1.66l-1.8 2.46l-1.44 1.52l-.34.14l-.6-.3l.06-.56l.32-.46l2-2.56l1.2-1.58l.8-.92l-.02-.1h-.06l-5.28 3.44l-.94.12l-.4-.4l.04-.6l.2-.2l1.6-1.1z" />
>                     </svg>
>                 </div>
>                 <div class="tLabel" id="claude">Claude</div>
>             </a>
> ```

Ohh i forgot to add bgLightTint class -_-

@deepakdeepu000 use prem's svg code then all will be good to go.

**Comment by itz-rj-here** [comment]
@prem-k-r can you open a pr and implement claude ai? As his code as many mistakes.?

**Comment by prem-k-r** [comment]
Let's wait some more hour if he wont fix it, then I will.. 
Also have to include translation

**Comment by prem-k-r** [comment]
#261

**Comment by itz-rj-here** [comment]
@XengShi can you close this pr please

**Pull request closed without merging**
