### PR TITLE
Update Language Selector

### PR DESCRIPTION
**Pull request by MestreWalla**
Page translation is complete, you can only add new languages

### CODE REVIEW

**Comment by MestreWalla** [comment]
Update

**Comment by XengShi** [comment]
Thank you for your hard work, I appreciate your effort. I noticed a few minor issues that need to be addressed. Could you please take a look and make the necessary fixes? Thank you!

IMG_20241013_004438

1. The "AI Tools" button is not responding.
2. The label should change from "Seems" to "Feels."

IMG_20241013_004607

3. I don't understand that language, but if it means "temperature," it is incorrect. This value does not represent the actual temperature; it refers to the "Feels Like Temperature," which considers factors like humidity and wind, making it feel warmer or cooler than the actual temperature.

**?** In Hindi, it is translated as "मौसम XY%" (where "मौसम" means weather), but this should reflect the **Humidity** level, not the weather.

IMG_20241013_004713

4. After applying the Čeština (Czech) and Português languages, the toggle buttons appear distorted. This is likely because these languages are less compact than others. Please consider reducing the text or adjusting the CSS to improve the design.

**Review by itz-rj-here — COMMENTED** [review]
Looks like some source of language errors.

**Comment by MestreWalla** [comment]
Improved translations, temperature in Fahrenheit fixed, I still haven't discovered what caused the glitch in the button, I don't remember doing anything related to it, I'm studying the code to see if I can fix it.

**Review by itz-rj-here — APPROVED** [review]

**Pull request merged**
