### PR TITLE
Firefox Reset Setting button width

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
**Fix firefox Setting Reset button width**
image

Image clearbutton color for dark theme, white to whitelike

Restricted how much scrollbar can move in google apps
image
to
image

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by XengShi** [comment]
https://github.com/user-attachments/assets/915878b0-7bb6-4142-bee5-2058fb32772c

**Comment by prem-k-r** [comment]
Date is centered with respect to UserText
I couldn't do it with rsepect to clock

**Comment by prem-k-r** [comment]
I can revert the center thing back, if you say so

**Comment by XengShi** [comment]
> I can revert the center thing back, if you say so

I would say 'NO' since it still not looking good.

**Comment by prem-k-r** [comment]
I understand, removed it

**Comment by XengShi** [comment]
image
Screenshot From 2024-12-08 22-02-59

I think solid background for usertext, date and shorcut;s label would be better than shadowsss

**Comment by prem-k-r** [comment]
I thought you wont like box thats why gone for shadow 😃

**Comment by prem-k-r** [comment]
can you check that pls
image
```
function updateTextShadow(hasWallpaper) {
    // Select elements
    const userText = document.getElementById('userText');
    const date = document.getElementById('date');
    const shortcuts = document.querySelectorAll('.shortcuts .shortcut-name');

    // Update styles for userText and date
    [userText, date].forEach(element => {
        if (hasWallpaper) {
            element.style.backgroundColor = 'var(--accentLightTint-blue)';
            element.style.padding = '6px 10px';
            element.style.width = 'fit-content';
            element.style.borderRadius = '100px';
        } else {
            element.style.backgroundColor = ''; // Reset to default
            element.style.padding = '';
            element.style.width = '';
            element.style.borderRadius = '';
        }
    });

    // Update styles for shortcuts
    shortcuts.forEach(shortcut => {
        if (hasWallpaper) {
            shortcut.style.textShadow = '1px 1px 15px rgba(255, 255, 255, 0.9), ' +
                '-1px -1px 15px rgba(255, 255, 255, 0.9), ' +
                '1px -1px 15px rgba(255, 255, 255, 0.9), ' +
                '-1px 1px 15px rgba(255, 255, 255, 0.9)';
        } else {
            shortcut.style.textShadow = 'none'; // Remove the text-shadow
        }
    });
}
```

**Comment by XengShi** [comment]
Not working!

**Comment by prem-k-r** [comment]
> Not working!

Which one?

**Comment by XengShi** [comment]
> > Not working!
> 
> Which one?

I am not getting solid background

**Comment by prem-k-r** [comment]
I haven't applied those changes in this PR

**Comment by prem-k-r** [comment]
> can you check that pls and do the changes image
> 
> ```
> function updateTextShadow(hasWallpaper) {
>     // Select elements
>     const userText = document.getElementById('userText');
>     const date = document.getElementById('date');
>     const shortcuts = document.querySelectorAll('.shortcuts .shortcut-name');
> 
>     // Update styles for userText and date
>     [userText, date].forEach(element => {
>         if (hasWallpaper) {
>             element.style.backgroundColor = 'var(--accentLightTint-blue)';
>             element.style.padding = '6px 10px';
>             element.style.width = 'fit-content';
>             element.style.borderRadius = '100px';
>         } else {
>             element.style.backgroundColor = ''; // Reset to default
>             element.style.padding = '';
>             element.style.width = '';
>             element.style.borderRadius = '';
>         }
>     });
> 
>     // Update styles for shortcuts
>     shortcuts.forEach(shortcut => {
>         if (hasWallpaper) {
>             shortcut.style.textShadow = '1px 1px 15px rgba(255, 255, 255, 0.9), ' +
>                 '-1px -1px 15px rgba(255, 255, 255, 0.9), ' +
>                 '1px -1px 15px rgba(255, 255, 255, 0.9), ' +
>                 '-1px 1px 15px rgba(255, 255, 255, 0.9)';
>         } else {
>             shortcut.style.textShadow = 'none'; // Remove the text-shadow
>         }
>     });
> }
> ```

Here is the code.. padding and all need to be adjusted.. I left it for you to decide the styling.. when usertext is single line and when it goes to second line.. solid bg appearing on top of analog clock for multiline..

**Comment by prem-k-r** [comment]
> ## Description
> TextShadow on Shortcuts name image
> 
> **Fix firefox Setting Reset button width** image
> 
> Image clearbutton color for dark theme, white to whitelike
> 
> Restricted how much scrollbar can move in google apps image to image
> 

Rest all these okay?

**Review by itz-rj-here — APPROVED** [review]

**Comment by prem-k-r** [comment]
@XengShi

**Pull request merged**
