### PR TITLE
Fixed Issue with Search Bar

### LINKED ISSUE #183: Add ability to select items from search autocomplete via keyboard
Now, when I want to select some autocomplete item, I need to click on it with a mouse. I want to have an option to stay on my keyboard, so the whole process is:

1. Search input is focused on the page load (e.g., `element.focus()`).
2. When I type something, autocomplete reveals.
3. I can use the Bottom and Top arrow keys to select a completed search query.
4. I press the Enter key, and it starts searching the selected query via the selected search engine (e.g., Google).

### PR DESCRIPTION
**Pull request by itz-rj-here**
When clicking on the Search Bar 2 times the outline of the Search Bar goes invisible. Now it's fixed.

### CODE REVIEW

**Comment by prem-k-r** [comment]
image
Ouline border when active is missing

**Comment by itz-rj-here** [comment]
> image
> Ouline border when active is missing

I will check that after 5 hours.

**Comment by itz-rj-here** [comment]
@prem-k-r Added outline color as you requested.

**Comment by itz-rj-here** [comment]
Sorry acidently clicked on the close button :)

**Comment by itz-rj-here** [comment]
@prem-k-r have you checked it still?

**Review by prem-k-r — CHANGES_REQUESTED** [review]
Doesn't seems to working correctly.

**Comment by itz-rj-here** [comment]
> Doesn't seems to working correctly.

I can see it works
w8 let me give you a recording.

**Comment by itz-rj-here** [comment]
Uhh I understand but chrome defaultly uses the focus for their search bar thats way it shows like this.

https://screenrec.com/share/25xwUkYCVH

**Comment by prem-k-r** [comment]
> Uhh I understand but chrome defaultly uses the focus for their search bar thats way it shows like this.
> 
> [screenrec.com/share/25xwUkYCVH](https://screenrec.com/share/25xwUkYCVH)

I know, but that's not the problem.

What happening after adding code
- When a new tab is opened or the current tab is reloaded, the search bar outline becomes visible, even though the cursor appears in the browser's search bar — which is not the desired behavior.
- However, if the user clicks on the search bar and then refreshes, the cursor appears in the extension's search bar with the outline active — this behavior is acceptable.

**Comment by itz-rj-here** [comment]
> > Uhh I understand but chrome defaultly uses the focus for their search bar thats way it shows like this.
> > [screenrec.com/share/25xwUkYCVH](https://screenrec.com/share/25xwUkYCVH)
> 
> I know, but that's not the problem.
> 
> What happening after adding code
> 
> * When a new tab is opened or the current tab is reloaded, the search bar outline becomes visible, even though the cursor appears in the browser's search bar — which is not the desired behavior.
> * However, if the user clicks on the search bar and then refreshes, the cursor appears in the extension's search bar with the outline active — this behavior is acceptable.

Hmm. Need to think more deeper. Let me try to fix it.

**Comment by prem-k-r** [comment]
I think we should discard this.

Instead implement that the search bar becomes active when clicked anywhere. I had done this last time when I was trying:
image
```
document.addEventListener("click", () => {
    const searchInput = document.getElementById("searchQ");
    searchInput.focus();
    searchbar.classList.add('active');
});
```
We just need to add a condition:
if (condition) { 
    // Check if the clicked element is a menu button
    return; // Do nothing if the menu button is clicked 
}

**Comment by itz-rj-here** [comment]
> I think we should discard this, as the browser's search bar cursor overrides it.
> 
> Instead implement that the search bar becomes active when clicked anywhere. I had done this last time when I was trying: image
> 
> ```
> document.addEventListener("click", () => {
>     const searchInput = document.getElementById("searchQ");
>     searchInput.focus();
>     searchbar.classList.add('active');
> });
> ```
> 
> We just need to add a condition: if (condition) { // Check if the clicked element is a menu button return; // Do nothing if the menu button is clicked }

Let me still try to find something if i find something

**Comment by itz-rj-here** [comment]
I found a useless idea from gpt for the first time. GPT gave me this extention to make it focus.

https://chromewebstore.google.com/detail/search-box-focus/amgmdnojamodmpfjaokfgpijhpcednjm

**Comment by itz-rj-here** [comment]
> I think we should discard this, as the browser's search bar cursor overrides it.
> 
> Instead implement that the search bar becomes active when clicked anywhere. I had done this last time when I was trying: image
> 
> ```
> document.addEventListener("click", () => {
>     const searchInput = document.getElementById("searchQ");
>     searchInput.focus();
>     searchbar.classList.add('active');
> });
> ```
> 
> We just need to add a condition: if (condition) { // Check if the clicked element is a menu button return; // Do nothing if the menu button is clicked }
> 
> one more condition, when searchbar is already active and clicked AI tools or Google apps button then inactive the seachbar.

Actually the clicking anywhere to make the searchbar active is a worst idea actually for me.

**Comment by prem-k-r** [comment]
> I found a useless idea from gpt for the first time. GPT gave me this extention to make it focus.
> 
> [chromewebstore.google.com/detail/search-box-focus/amgmdnojamodmpfjaokfgpijhpcednjm](https://chromewebstore.google.com/detail/search-box-focus/amgmdnojamodmpfjaokfgpijhpcednjm)

check there github 
https://github.com/MikesGlitch/Focus-First-Input/tree/master/src

**Comment by itz-rj-here** [comment]
> > I found a useless idea from gpt for the first time. GPT gave me this extention to make it focus.
> > [chromewebstore.google.com/detail/search-box-focus/amgmdnojamodmpfjaokfgpijhpcednjm](https://chromewebstore.google.com/detail/search-box-focus/amgmdnojamodmpfjaokfgpijhpcednjm)
> 
> check there github https://github.com/MikesGlitch/Focus-First-Input/tree/master/src

I already tried it. I don't still see any solution for this. 
I think we should close this pr. I don't see any solution for this for now. As the chrome browser defaultly focuses to their searchbar.

What you think? If you agree i will close this pr.

**Comment by prem-k-r** [comment]
ok

**Review by prem-k-r — APPROVED** [review]
Great

**Pull request merged**
