### PR TITLE
[feat]: added location disable option

### PR DESCRIPTION
**Pull request by mohan123re**
added location disable option

### CODE REVIEW

**Comment by WhitePoodleMoth** [comment]
Hi, I noticed that this PR seems to be a duplicate of #24, which already addresses the same issue #23.

**Review by WhitePoodleMoth — APPROVED** [review]
Everything is working. If location services are disabled, the location will default to 'Earth'

**Comment by mohan123re** [comment]
merge pr

**Review by itz-rj-here — APPROVED** [review]
Working properly.

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
image
image
There is an issue here. When you close your browser completely and again open it, it shows Earth even in the settings the location hide is off. 
Requesting to fix this issue first.

**Comment by itz-rj-here** [comment]
@mohan123re your code has some issues fix it and again add a pull request.

**Pull request merged**
