### PR TITLE
Rearranged Google app icons, removed text bgcolor, Firefox scrollbar

### PR DESCRIPTION
**Pull request by prem-k-r**
image
to
image

also
image
to
image

edit:
removed: Bussiness Profile ~Manager~, due to firefox
image

### CODE REVIEW

**Comment by XengShi** [comment]
image

Can you re-arrange shortcuts and we can simply arrange them for users convenience I don't think most of the user gonna use that business profile, place shortcuts like youtbe, keep, maps, photos, calendar, drive... first

**Comment by prem-k-r** [comment]
okay

**Comment by XengShi** [comment]
I added these lines previoulsy remove them and see if everything still work

```

position: absolute;
  font-size: 0.8rem;
  background-color:  var(--bg-color-blue);
  bottom: 0;
```

**Comment by prem-k-r** [comment]
> I added these lines previoulsy remove them and see if everything still work
> 
> ```
> 
> position: absolute;
>   font-size: 0.8rem;
>   background-color:  var(--bg-color-blue);
>   bottom: 0;
> ```

nah, need them
```
	position: absolute;
    font-size: 0.8rem;
    bottom: 0;
```

**Comment by XengShi** [comment]
Can you test it on Firefox and look out the scrollbar on google apps container.

if seeing ugly scrollbar try replacing scrollbar code with
```
/* Customize scrollbar to appear on the border */
/* For Chrome */
.icon-container::-webkit-scrollbar {
    width: 5px;
    height: 5px;
    /* For horizontal scrollbar */
}

.icon-container::-webkit-scrollbar-track {
    background-color: transparent;
    border-radius: 30px;
}

.icon-container::-webkit-scrollbar-thumb {
    background-color: var(--darkColor-blue);
    border-radius: 30px;
}

.icon-container::-webkit-scrollbar-thumb:hover {
    background-color: var(--darkerColor-blue);
    border-radius: 30px;
}

/* For Firefox */
.icon-container {
    scrollbar-width: thin;
    /* Thin scrollbar */
    scrollbar-color: var(--darkColor-blue) transparent;
    /* Thumb color and track color */
    overflow-x: hidden;
    /* Hide horizontal scrollbar */
}

/* ----------------- End of Google App Menu ----------------- */
```

**Comment by prem-k-r** [comment]
I'm getting different scrollbar, without scrollbar modification
https://github.com/user-attachments/assets/798ee92d-bbfb-4b52-a3d0-10bee74f0114
also Business Profile Manager is showing in 3 lines

no such problems in edge

**Comment by prem-k-r** [comment]
https://github.com/user-attachments/assets/46464d4e-1a0c-4bc1-a13b-c44b9bf3d97e

[…](#)

> Can you test it on Firefox and check out the scrollbar on google apps container.
> 
> if seeing ugly scrollbar try replacing scrollbar code with
> 
> ```
> /* Customize scrollbar to appear on the border */
> /* For Chrome */
> .icon-container::-webkit-scrollbar {
>     width: 5px;
>     height: 5px;
>     /* For horizontal scrollbar */
> }
> 
> .icon-container::-webkit-scrollbar-track {
>     background-color: transparent;
>     border-radius: 30px;
> }
> 
> .icon-container::-webkit-scrollbar-thumb {
>     background-color: var(--darkColor-blue);
>     border-radius: 30px;
> }
> 
> .icon-container::-webkit-scrollbar-thumb:hover {
>     background-color: var(--darkerColor-blue);
>     border-radius: 30px;
> }
> 
> /* For Firefox */
> .icon-container {
>     scrollbar-width: thin;
>     /* Thin scrollbar */
>     scrollbar-color: var(--darkColor-blue) transparent;
>     /* Thumb color and track color */
>     overflow-x: hidden;
>     /* Hide horizontal scrollbar */
> }
> 
> /* ----------------- End of Google App Menu ----------------- */
> ```

**Comment by XengShi** [comment]
@prem-k-r 
what OS are you using? I’m seeing the same scrollbar on Linux (Manjaro), but on Windows, it looks different.

**Comment by prem-k-r** [comment]
Windows

**Review by itz-rj-here — COMMENTED** [review]
https://screenrec.com/share/T42rOD5zJa
Tooltip is causing some hover showing issue

**Comment by prem-k-r** [comment]
> [screenrec.com/share/T42rOD5zJa](https://screenrec.com/share/T42rOD5zJa) Tooltip is causing some hover showing issue

Did you mean the hover text not showing after clicking?
It's an intentional feature, lol. After clicking, it won't show for 1.5 seconds.

Earlier, when the cursor remained on top of the 9-dots after clicking, the text would still appear. I introduced a delay when I raised the PR in your forked repo.

**Comment by prem-k-r** [comment]
btw @XengShi, what’s your opinion on the icons? They seem inconsistent.
image

some like Gmail icon, i dont really like it.
image

Docs, similar svg available like of sheets, slides
image
image

**Comment by XengShi** [comment]
> btw @XengShi, what’s your opinion on the icons? They seem inconsistent.
> image
> 
> some like Gmail icon, i dont really like it.
> image
> 
> Docs, similar svg available like of sheets, slides
> image
> image
> 

Yes they are inconsistent!

**Comment by itz-rj-here** [comment]
> > [screenrec.com/share/T42rOD5zJa](https://screenrec.com/share/T42rOD5zJa) Tooltip is causing some hover showing issue
> 
> Did you mean the hover text not showing after clicking? It's an intentional feature, lol. After clicking, it won't show for 1.5 seconds.
> 
> Earlier, when the cursor remained on top of the 9-dots after clicking, the text would still appear. I introduced a delay when I raised the PR in your forked repo.

Oo

**Comment by itz-rj-here** [comment]
@XengShi choice one from here.
image

**Comment by itz-rj-here** [comment]
I think we should release a new version after this.

**Comment by prem-k-r** [comment]
image
image
image

**Comment by XengShi** [comment]
Looking nice

**Comment by itz-rj-here** [comment]
> Looking nice 

Agreed

**Comment by prem-k-r** [comment]
> I think we should release a new version after this.

after this two pending PR, missing czech translation, fold arrow remove (+ai tool bug fix), Final touch wherever needed.. we can go for directly v2.5 lol..

**Comment by itz-rj-here** [comment]
> > I think we should release a new version after this.
> 
> after this two pending PR, missing czech translation, fold arrow remove (+ai tool bug fix), Final touch wherever needed.. we can go for directly v2.5 lol.. 

Huh.

**Pull request merged**
