### PR TITLE
Updated the firefox manifests. Also fixed the icon of the home page tab.

### PR DESCRIPTION
**Pull request by itz-rj-here**

### CODE REVIEW

**Comment by itz-rj-here** [comment]
I will fix the conflicts after i come home.

**Comment by ZiClaud** [comment]
Could you also remove extra access for Firefox too?
Also, I've noticed the Firefox version is still 1.3, could you update it?
The file to edit is `manifest(firefox).json`

**Comment by XengShi** [comment]
> I will fix the conflicts after i come home.

I fixed it, now you can modify manifest for Firefox.

**Comment by itz-rj-here** [comment]
> > I will fix the conflicts after i come home.
> 
> I fixed it, now you can modify manifest for Firefox.

As you say. But i just came from school. I need to go to bath. Doing it after i finish taking bath.

**Comment by itz-rj-here** [comment]
@XengShi, could you please review this PR?

**Comment by itz-rj-here** [comment]
@XengShi ?

**Comment by XengShi** [comment]
Getting some warnings

Screenshot 2024-10-20 at 20-31-15 Debugging - Runtime _ this-firefox

**Comment by itz-rj-here** [comment]
> Getting some warnings
> 
> Screenshot 2024-10-20 at 20-31-15 Debugging - Runtime _ this-firefox

on it

**Comment by itz-rj-here** [comment]
@XengShi Done. Just removed the president thingy and it fixed nice :)

**Comment by itz-rj-here** [comment]
I forgot that its the manifest v3 not v2 that was my mistake sorry :)

**Pull request merged**
