### PR TITLE
Searchbar Shortcut

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
Focuses searchbar input on / keypress

## Related issue
2.
image

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
we can add more lol.. t for todo, g for google apps, a for AI tools,m for menu

**Comment by Thunder-Blaze** [comment]
hmm Sure I'll be doing this by tonight

**Comment by prem-k-r** [comment]
nah, I'm asking if we should add those too

**Comment by prem-k-r** [comment]
/ is default shortcut for search in many platform.. but not others

**Comment by Thunder-Blaze** [comment]
oh lmk when you decide on which shortcuts to add

And I was thinking myself of adding key shortcuts, also whenever we open a new tab the default focus goes to the searchbar of browser, have to do smth about that too

**Comment by prem-k-r** [comment]
> And I was thinking myself of adding key shortcuts as they help a lot, also whenever we open a new tab the default focus goes to the searchbar of browser, have to do smth about that too

we tried to do it earlier.. but unable to do it.. cant override browser's
see if you can find a solution

**Comment by prem-k-r** [comment]
```
document.addEventListener('keydown', function (event) {
    if (event.altKey && event.shiftKey && event.key.toLowerCase() === 'd') {
        const darkThemeRadio = document.getElementById('darkTheme');
        if (darkThemeRadio) {
            darkThemeRadio.checked = true;
            darkThemeRadio.dispatchEvent(new Event('change'));
        }
    }
});
```
`alt` + `shift` + `d` : switch to dark theme instantly
:p

**Review by itz-rj-here — APPROVED** [review]

**Review by Thunder-Blaze — APPROVED** [review]

**Comment by Thunder-Blaze** [comment]
@XengShi when can we merge this one ?
I'd really like keyboard shortcuts :)

**Comment by prem-k-r** [comment]
> ## Description
> Focuses searchbar input on / keypress
> 
> ## Related issue
> 
> image


@XengShi , umm you dont like it?

Only added keyboard shortcuts for search bar, we already have right arrow `>` for bookmark

**Comment by prem-k-r** [comment]
we can add more if you want, like to open Google apps, AI tools, To-Do, Menu, shortcuts quicklaunch..
voice typing, dark theme, clock switch(analog-digital).. etc

**Comment by itz-rj-here** [comment]
@XengShi You can merge this. As a user already suggested for this changes. It's working fine for me. When you click the "/" button it will focus the searchbar. As the default chrome new tab works.

**Review by itz-rj-here — APPROVED** [review]

**Comment by XengShi** [comment]
> @XengShi You can merge this. As a user already suggested for this changes. It's working fine for me. When you click the "/" button it will focus the searchbar. As the default chrome new tab works.

Okay, please add this in the chrome branch

**Comment by prem-k-r** [comment]
> > @XengShi You can merge this. As a user already suggested for this changes. It's working fine for me. When you click the "/" button it will focus the searchbar. As the default chrome new tab works.
> 
> Okay, please add this in the chrome branch

it's there

**Pull request merged**
