### PR TITLE
Change the extension and page/tab icon color based on the selected theme

### LINKED ISSUE #119: Change page/tab icon according to selected color theme
Now, there is always a blue icon (use the color of the default color theme). I think a better approach is to switch icons according to the selected color theme. So, when I switch to green, the icon also changes to a green variant.

### PR DESCRIPTION
**Pull request by prem-k-r**
Tested on Windows/Chrome, Edge, Firefox, Brave

Closes #119

### CODE REVIEW

**Comment by prem-k-r** [comment]
Not facing any issue but in developer console there is an error
image
@XengShi can you please check
also need to verify that it works in other browsers too

**Review by itz-rj-here — APPROVED** [review]
Wow. I really appreciate your changes. Great work.

**Comment by itz-rj-here** [comment]
> Not facing any issue but in developer console there is an error
> image
> @XengShi can you please check
> also need to verify that it works in other browsers too

Maybe the format of the image is causing the issue. Try changing the image format if it fixes.

**Comment by XengShi** [comment]
I think changing png to ico will fix that error

**Comment by prem-k-r** [comment]
> I think changing png to ico will fix that error

It didnt, but I got it. 
I was using image 180x180, changed to 128x128, and console error dissapeared.

**Comment by itz-rj-here** [comment]
huh what changes you did 👀

**Comment by prem-k-r** [comment]
A quick question, does the extension supports in Opera too?

**Comment by XengShi** [comment]
> A quick question, does the extension supports in Opera too?

Yess

**Comment by prem-k-r** [comment]
Ok
I checked on chrome and edge
Currently working:
+ Chrome 
     - Tab icon: yes, but for a split second it shows the default blue icon. Have to put it in DOMContentLoaded event. I'll get it to later 
     - Extension icon: yes

+ Edge
     - Tab icon: No. Showing white circular zigzag icon for all theme 
     - Extension icon: yes

Also I noticed now that the icon I edited, uploaded by RJ had a padding. So icons will appear a little bit smaller. I'll re edit and upload after fixing code

**Comment by prem-k-r** [comment]
I just installed Firefox to check, and both the tab icon and extension icon color changes are working fine.

Other things I noticed:
- The manual installation mentioned in the `Readme.md` is a temporary method. The extension disappears after the browser is restarted.
- I was suprised to see #81 (+ #112 = `When opening or refreshing a new tab with/without a non-default theme, the default theme and both clock (analog and digital) briefly appear for a split second`) happens everytime.
In Chrome, this only happens occasionally.

**Comment by itz-rj-here** [comment]
Idk i just don't use those.

**Comment by prem-k-r** [comment]
> Ok I checked on chrome and edge Currently working:
> 
> * Chrome
>   
>   * Tab icon: yes, but for a split second it shows the default blue icon. Have to put it in DOMContentLoaded event. I'll get it to later
>   * Extension icon: yes
> * Edge
>   
>   * Tab icon: No. Showing white circular zigzag icon for all theme
>   * Extension icon: yes
> 



This edge stuff already in `XegShi:main` 
Checked on brave too, working fine

**Comment by prem-k-r** [comment]
@XengShi fixed conflicts

**Pull request merged**
