### PR TITLE
Added an option to input location manually + Translation

### PR DESCRIPTION
**Pull request by prem12321kumar**

### CODE REVIEW

**Comment by prem12321kumar** [comment]
image

**Review by itz-rj-here — COMMENTED** [review]
This is a problem. It utilizes a location that is common to the place name the user enters at random if we use a location that is not listed in the weatherapi.
You included a Learn More option as well. However, it takes the user to the Weatherapi documentation. Only those who use the weather API on development should refer to the documentation; those who simply do not use the weather API or are unaware of it should not.
You could use this link https://www.weatherapi.com/weather/
Not the docs one.

**Comment by itz-rj-here** [comment]
It could be better if a user could have a search suggestion on that too. Let me ask Minuga about it.

**Comment by prem12321kumar** [comment]
It's able to take additional parameters apart from the city, such as latitude-longitude, US ZIP codes, UK PINs, and more. These details are mentioned in the documentation, which is why I’ve included the link. However, the issue of inputting a location not available in the WeatherAPI remains.

**Comment by prem12321kumar** [comment]
It shows Mumbai for me, which is incorrect as it's being fetched from the IP location. Personally, I use latitude and longitude for more accurate results.

**Comment by itz-rj-here** [comment]
I asked Minuga about it. He said he will look into it.

**Comment by prem12321kumar** [comment]
just changed link to "https://www.weatherapi.com/docs/#intro-request-param"
image

**Review by itz-rj-here — APPROVED** [review]
Looks fine to me.
I will say XengShi to merge this pr later. Thanks for the contribution.

**Comment by itz-rj-here** [comment]
Can you explain what you did here?

**Comment by itz-rj-here** [comment]
Hello there?

**Comment by itz-rj-here** [comment]
Cause it is linked with your forked repo. Anyways thanks again for adding the missing translation.

**Comment by prem12321kumar** [comment]
ohk. Done, submitting for review.

Changelog:
Fix:
-Consolidated date formatting logic to eliminate redundant code in the display of the date.

Adding:
-Added an option to input the location manually.
-Hindi formatting: Show full name for month
-customized date displayed in Hindi: full month names, truncated week day
-Added missing translations ids in English and translated for Hindi.

Left:
image
"menuCloseButton:hover::after": "Close", need translation, probably have to use new function. I might try later or someone else can do.
-Translation left for other languages, except Hindi

**Comment by prem12321kumar** [comment]
conflicted

**Comment by ceskyDJ** [comment]
Could you please trash me after merging? I'd like to update the Czech translation after these changes are approved.

**Comment by itz-rj-here** [comment]
I would need to check it first. I have school today. So i need to check it after i come from school. Also Minuga did some changes too. After ensuring all pr and changes i will review your pr too. I will come after 10 hours. Until i will give @Minuga-RC to handle everything until i come home. 
And thanks for your hard work. I really do appreciate it.

**Comment by Minuga-RC** [comment]
Yea you did a lotta changed I gotta check that out later from my PC

**Comment by prem12321kumar** [comment]
@Minuga-RC Actually after analog clock addition there was a conflict. There was redundant code in date formatting earlier and I did some changes, created a variable, but after last day's analog merge it was fix in analog too, there was a conflict. I was not sure how to fix the conflict, so I copied the code later part that i didn't change earlier from new code(after analog merge). So in script.js old line around 135 and my line 150 I have not done anything, It is showing that already merged rn but I did something unnecessary, didn't know.. shouldn't have copied from new. 
Sorry for that, you may ignore code checking after the catch block of weather stuff (line 150) in script.js

**Comment by prem12321kumar** [comment]
let me create a fresh pr

**Comment by prem12321kumar** [comment]
#78

**Pull request closed without merging**
