### PR TITLE
Update languages.js

### PR DESCRIPTION
**Pull request by Guy-Berryman**
fix zh lang

### CODE REVIEW

**Review by MestreWalla — APPROVED** [review]
thanks

**Review by itz-rj-here — APPROVED** [review]
Great

**Comment by XengShi** [comment]
@MestreWalla 
After reloading the page, Text "Double tap to edit" automatically get back to default text from languages.js kindly fix that!

**Comment by itz-rj-here** [comment]
Already faced that issue. Looking for the fixes.

**Pull request merged**
