### PR TITLE
Added right padding in 'feelsLike' to proper display in some languages

### PR DESCRIPTION
**Pull request by prem12321kumar**
added padding to Seems
image
changed to
image

### CODE REVIEW

**Comment by ceskyDJ** [comment]
It looks way better, but there is one other thing — a space missing between the number and its unit (correct is e.g. 27 °C). I don't know how it should be elsewhere, but in Czech there had to be an (unbreakable) space between them.

**Comment by ceskyDJ** [comment]
And over another thing… We use decimal commas instead of decimal dots, so, e.g., "9,1 °C" is correct.

**Comment by itz-rj-here** [comment]
@prem12321kumar

**Comment by prem12321kumar** [comment]
that's a bit complicated, have a rough idea, might or might not work, will try later.

for now in Czech formatting can change displayed date format (Mon, Oct 21) only.

**Comment by prem12321kumar** [comment]
@ceskyDJ 
image

**Comment by ceskyDJ** [comment]
Oh, there is another mistake I didn't see before. There has to be a space between number and ° in temperature. This brings me to one question: Shouldn't we print °C, resp. °F there? Degree is an unit of angle…  Anyway, a space is missing in both cases for Czech.

**Comment by prem12321kumar** [comment]
> Oh, there is another mistake I didn't see before. There has to be a space between number and ° in temperature. This brings me to one question: Shouldn't we print °C, resp. °F there? Degree is an unit of angle… Anyway, a space is missing in both cases for Czech.

I totally understand and agree with your point. The correct units are indeed °C and °F, as "degree" shouldn’t stand alone. However, adding "C" or "F" will result in a longer display, which is why I initially left it as it was, just the numbers with the degree symbol and without the degree symbol, it looks odd to me.

Maybe later I can try adjusting the format, like displaying 21^(°C or °F in a smaller font)

**Pull request closed without merging**
