### PR TITLE
Removed Search Engines, Switch to Chrome Search API

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
- Update manifest version to 2.6

- Deleted Search engines and related things from html and js (languages and css not deleted)

- Switched to Chrome Search API

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Remove the text from the menu section tooo.

**Comment by prem-k-r** [comment]
yeah, It's in draft.. I'm still working

**Comment by prem-k-r** [comment]
It's done.
commented out code.. should i delete them instead? @XengShi

**Comment by XengShi** [comment]
> It's done.
> commented out code.. should i delete them instead? @XengShi 

Yes you can delete them

**Comment by prem-k-r** [comment]
@XengShi How much time they took to review earlier after updating in store? 
Weatherapi's limit gonna reach on 23-24th. Depending upon review time we can comment existing and add new keys.. and submit for review like 22nd?

**Comment by XengShi** [comment]
> @XengShi How much time they took to review earlier after updating in store? 
> Weatherapi's limit gonna reach on 23-24th. Depending upon review time we can comment existing and add new keys.. and submit for review like 22nd?
> 

2-3 days or even longer

**Comment by prem-k-r** [comment]
Ohk, so when are you planning to submit, today or tomorrow?

**Comment by XengShi** [comment]
> Ohk, so when are you planning to submit, today or tomorrow? 

Let me check the changes

**Comment by prem-k-r** [comment]
You can check the theme flashing PR.. if it's working.. merge and sync before final version..
+ 2 Weather ApI

Zoom slider also missing.. I was checking the code.. probably some more changes have been made that's not there in the branch

**Comment by XengShi** [comment]
image

Why you didn't removed search with section, remove that completly instead of hiding, and search suggestion seems not working.

**Comment by prem-k-r** [comment]
> image
> 
> Why you didn't removed search with section, remove that completly instead of hiding, and search suggestion seems not working.

After removing search with completely, the whole rightdiv shifting downward..
checking search suggestion

**Comment by XengShi** [comment]
> > image
> > 
> > Why you didn't removed search with section, remove that completly instead of hiding, and search suggestion seems not working.
> 
> After removing search with completely, the whole rightdiv shifting downward..
> checking search suggestion

I see that, you can remove unused css codes

**Comment by XengShi** [comment]
@prem-k-r I am thinking of replacing 'search with' thing with random quotes. (Quotes will change after every refresh.)

**Comment by prem-k-r** [comment]
Looks nice

**Comment by prem-k-r** [comment]
You can add this in main branch too.. it will be off by default.. linked with hide search engines toggle.. when toggle on, this toggle to show/hide random quotes become active

**Review by itz-rj-here — APPROVED** [review]

**Pull request merged**
