### PR TITLE
Removed fold/unfolding for shortcuts in AI Tools  and Collapse AI Tools when clicked outside

### PR DESCRIPTION
**Pull request by prem-k-r**
Just commented out the related snippets---- deleted

### CODE REVIEW

**Comment by prem-k-r** [comment]
I'm not sure where to add the EventListener to collapse the AI tools when clicking outside while they are expanded.
@XengShi, could you please take care of it?

**Comment by prem-k-r** [comment]
Okay done that too, collapsing the AI tools when clicking outside while they are expanded

**Comment by prem-k-r** [comment]
> image
> 
> Shortcuts can't breath!!!

when this is happening?

**Comment by prem-k-r** [comment]
@XengShi uncommented one line, see if this fixes it

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
What you did bruh -_-

https://screenrec.com/share/Lhs471iEYa

**Comment by prem-k-r** [comment]
> What you did bruh -_-
> 
> [screenrec.com/share/Lhs471iEYa](https://screenrec.com/share/Lhs471iEYa)

I can't recreate this, can you please check again if this fixed it now or not

**Comment by itz-rj-here** [comment]
image
image
Working properly now. 

Can you just add one more thing. Can you make a click delay on AI Tools button. Like 1 Second delay. Cause clicking on the AI Tools button makes some weird animation on showing the AI Tools.
https://screenrec.com/share/FzaCxNVElP

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Add a delay on clicking on the AI Tools Button Please.

**Comment by prem-k-r** [comment]
I dont get it. Do you mean when clicking quickly on AI Tools

**Comment by itz-rj-here** [comment]
> I dont get it. Do you mean when clicking quickly on AI Tools

Yup

**Review by itz-rj-here — APPROVED** [review]
Ok for now

**Pull request merged**
