### PR TITLE
i18n: Update Czech according to last changes of original strings

### PR DESCRIPTION
**Pull request by ceskyDJ**

### CODE REVIEW

**Comment by ceskyDJ** [comment]
I have one note here. @prem12321kumar did this change:
```diff
- "userLoc": "Your location (City/Latitude,Longitude)",
+ "userLoc": "Your location (City or Latitude,Longitude)",
```

If I update Czech according to this change, it'll be a complete mess so that nobody can understand it:
```diff
- "userLoc": "Vaše poloha (město / zeměpisná šířka, zeměpisná délka)",
+ "userLoc": "Vaše poloha (město nebo zeměpisná šířka, zeměpisná délka)",
```

I think the best solution for this is to make it more clear in all languages, something like:
```diff
English
- "userLoc": "Your location (City or Latitude,Longitude)",
+ "userLoc": "Your location — city or geocoordinates (e.g., `50.09118602632995,14.401595046959825`)",

Czech
- "userLoc": "Vaše poloha (město nebo zeměpisná šířka, zeměpisná délka)",
+ "userLoc": "Vaše poloha – město nebo zeměpisné souřadnice (např. `50.09118602632995,14.401595046959825`)",
```

Of course, we may not need such precision here. I just copied the coordinates from Google Maps.

**Comment by ceskyDJ** [comment]
There is another way (maybe better?):
```diff
English
- "userLoc": "Your location (City or Latitude,Longitude)",
+ "userLoc": "Your location — city or geocoordinates (in form: latitude,longitude)",

Czech
- "userLoc": "Vaše poloha (město nebo zeměpisná šířka, zeměpisná délka)",
+ "userLoc": "Vaše poloha – město nebo zeměpisné souřadnice (ve tvaru: šířka,délka)",
```

**Comment by ceskyDJ** [comment]
I just noticed another thing about the digital clock. What about this change?
```diff
English
- "digitalclockinfo": "Enable the digital clock",
+ "digitalclockinfo": "Switch to the digital clock",

Czech
- "digitalclockinfo": "Zapne digitální hodiny",
+ "digitalclockinfo": "Přepne hodiny na digitální",
```

**Comment by prem12321kumar** [comment]
> I just noticed another thing about the digital clock. What about this change?
> 
> ```diff
> English
> - "digitalclockinfo": "Enable the digital clock",
> + "digitalclockinfo": "Switch to the digital clock",
> 
> Czech
> - "digitalclockinfo": "Zapne digitální hodiny",
> + "digitalclockinfo": "Přepne hodiny na digitální",
> ```

Yeah better.
You can change, I think.

**Comment by prem12321kumar** [comment]
For location we have to check if it's fit in visible area. 
I suggest:

Your City or GeoCoordinates (Lat,Long)

or
Your City or GeoCoordinates (Latitude,Longitude)
if it's visible

**Comment by ceskyDJ** [comment]
Ok, for Czech, this fits the input: `Město nebo souřadnice (šířka,délka)`. English equivalent: `Your City or Coordinates (Latitude,Longitude)`.

**Comment by ceskyDJ** [comment]
> For location we have to check if it's fit in visible area.

By the way, the current Czech translation doesn't fit the input.

**Comment by prem12321kumar** [comment]
> Ok, for Czech, this fits the input: `Město nebo souřadnice (šířka,délka)`. English equivalent: `Your City or Coordinates (Latitude,Longitude)` (also fits).

Nice, Change it

**Comment by ceskyDJ** [comment]
> Nice, Change it

@XengShi was a bit faster :D. I opened PR #125 for it.

**Pull request merged**
