### PR TITLE
Added random wallpaper option and warning for Large images

### LINKED ISSUE #253: Adding a Background Picture
It will be impressive if you add an option to toggle fetching an aesthetic random Background Picture every day or in some hours.

### PR DESCRIPTION
**Pull request by prem-k-r**
Closes #253 
image
random image wp if clicked on button
daily new random images if wp selected from random

### CODE REVIEW

**Comment by prem-k-r** [comment]
need help in css with something like
image

**Comment by prem-k-r** [comment]
Done, please review.
Only styling left: combining upload and random as in above image.

**Comment by prem-k-r** [comment]
@XengShi

**Comment by XengShi** [comment]
> need help in css with something like
> image
> 

Very simple,

Just keep upload wallpaper thing as it is, and for that arrow container.
Add border which matches the background

**Comment by XengShi** [comment]
https://github.com/user-attachments/assets/6a34a4a4-6534-418b-a59f-0ac07bc5d821

Why you are changing its shape on resizing!!!

**Comment by prem-k-r** [comment]
> Screencast.From.2024-12-02.14-11-47.mp4 
> Why you are changing its shape on resizing!!!

ah 😔
I'll look into it

**Comment by XengShi** [comment]
> > Screencast.From.2024-12-02.14-11-47.mp4 
> > Why you are changing its shape on resizing!!!
> 
> ah 😔
> Undesired outcome.. I'll look into it

Prem, come on telegram

**Comment by prem-k-r** [comment]
> Screencast.From.2024-12-02.14-11-47.mp4 
> Why you are changing its shape on resizing!!!

#258

**Pull request merged**
