### PR TITLE
Search suggestions without proxy

### PR DESCRIPTION
**Pull request by prem-k-r**
for firefox

### CODE REVIEW

**Comment by XengShi** [comment]
> for firefox

Explain more if this will only work on firefox please push the changes to firefox branch

**Comment by prem-k-r** [comment]
We should changed in main branch too.
Only changed the file manifest (**firefox**)
Related #345, Firefox uses manifest v2.. so have different syntax

**Comment by prem-k-r** [comment]
We have to update the firefox branch too with latest changes

**Comment by XengShi** [comment]
> We have to update the firefox branch too with latest changes

Does search suggestion works for you without proxy?

**Comment by prem-k-r** [comment]
After applying this change, yes

**Pull request merged**
