### PR TITLE
Search Recommendation added

### PR DESCRIPTION
**Pull request by Minuga-RC**
+ Search Recommendation
- Some unwanted things removed

### CODE REVIEW

**Review by ZiClaud — CHANGES_REQUESTED** [review]
```
- <a class="tiles" href="https://github.com/Code-by-imtiyaz/materialYouNewTab">
+ <a class="tiles" href="https://github.com/Minuga-RC/BetterMaterialYouNewTab">
 ```
 The audacity to change the link to this repo to your own repository .-.

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Also fix the conflicts too.

**Comment by Minuga-RC** [comment]
Oh god I'm sorry I was making like my own better version of it and later decided to make a pull req here but forgot about this 
> ```
> - <a class="tiles" href="https://github.com/Code-by-imtiyaz/materialYouNewTab">
> + <a class="tiles" href="https://github.com/Minuga-RC/BetterMaterialYouNewTab">
>  ```
>  The audacity to change the link to this repo to your own repository .-.

**Comment by Minuga-RC** [comment]
I currently can't do anything as my computer recently just broke down :( 
I'm literally replying to u in the mobile app 
> Also fix the conflicts too.

**Comment by ZiClaud** [comment]
Also put on the commits what you did, don't write "Lotta things done"

**Comment by itz-rj-here** [comment]
I can understand your issue. You can use chrome app to fix this as your computer broke and if you still want to fix this conflict though a computer, I would prefer you to keep it on draft until you fix your conputer and fix the conflicts too.

**Pull request closed without merging**
