### PR TITLE
Added GNU General Public License v3.0 (GPL-3.0) License for the Extention

### PR DESCRIPTION
**Pull request by itz-rj-here**
- **Warranty Disclaimer**: The software is provided "as is," without any warranty. If you encounter any bugs or issues, please report them in our GitHub repository, and we will do our best to address them.
  
- **Commercial Use**: Please note that this software cannot be sold or used for commercial purposes. This is a specific restriction I’ve added to ensure the project remains free for everyone.

- **Modified Versions**: While we encourage contributions and modifications, please understand that we cannot provide support for issues arising from modified versions of the software that are not derived from the original code.

### CODE REVIEW

**Comment by itz-rj-here** [comment]
Requesting for review from @XengShi @prem-k-r @ceskyDJ @ZiClaud. If anyone of you see any mistakes or any requirement changes needed here let me know.

**Comment by prem-k-r** [comment]
For now i see 2 things. Later I'll check in detail 
Copyright year:  it is generally current year for completed project or for ongoing project: began year - current year
So Copyright (c) 2023-2024 XengShi


Second, I saw selling is permitted, it should be prohibited

**Comment by itz-rj-here** [comment]
> For now i see 2 things. Later I'll check in detail Copyright year: it is generally current year for completed project or for ongoing project: began year - current year So Copyright (c) 2023-2024 XengShi
> 
> Second, I saw selling is permitted, it should be prohibited

Thanks for the check i will recorrect it.

**Comment by itz-rj-here** [comment]
> For now i see 2 things. Later I'll check in detail Copyright year: it is generally current year for completed project or for ongoing project: began year - current year So Copyright (c) 2023-2024 XengShi
> 
> Second, I saw selling is permitted, it should be prohibited

The selling thing was defaultly written. Thats way. I wouldn't saw that if you don't mention it to me.

**Comment by itz-rj-here** [comment]
@prem-k-r how about now?

**Comment by prem-k-r** [comment]
I don't really know how this things work. I put it in ChatGPT, see what it says:
Your modified license text creates a Non-Commercial variant of the MIT License, which restricts the use of the software to non-commercial purposes. However, it’s important to note that this version isn’t officially recognized as the MIT License because MIT itself does not allow restricting commercial use in its standard terms. Here’s a breakdown of considerations:

1. Custom License: By adding a "Non-Commercial Use Only" restriction, this license becomes a custom license. You may wish to clearly state it as something like "MIT License (Non-Commercial)" or simply "Non-Commercial License" to avoid any legal confusion, as users may assume that the MIT License allows commercial use by default.


2. Compatibility and Community Acceptance: The open-source community generally prefers licenses without restrictions on commercial use, like MIT or Apache. If you intend to submit your project to certain open-source directories or repositories, they might not accept this modified version since it doesn’t adhere to the Open Source Initiative’s definition.


3. Alternative Licenses: If a non-commercial license is essential, consider recognized options such as:

Creative Commons Non-Commercial Licenses (CC BY-NC): Though more common in content (e.g., documentation), it’s well-suited for non-commercial use and is widely understood.

GNU Affero General Public License (AGPL) or MPL with Non-Commercial Clauses: These are also restrictive, but you can consider variations based on the level of restriction needed.




Your license text itself appears legally sound if your goal is to allow non-commercial use only. Just keep in mind that creating a custom license may reduce compatibility with other open-source projects or platforms.

**Comment by prem-k-r** [comment]
If you want to enforce non-commercial use while keeping the license simple and recognizable, here are two widely used alternatives:


---

1. Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)

This license allows others to copy, distribute, and modify the work, as long as it’s for non-commercial purposes, and they provide appropriate credit. It's simple and familiar to many users.

How to Use It:

Include a LICENSE file in your repository with the full CC BY-NC 4.0 license text. You can find it here.

Add a note at the top of your README to make it clear:
"This project is licensed under the Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)."


Key Points of CC BY-NC 4.0:

Non-commercial: The software cannot be used for commercial purposes.

Attribution: Requires that all copies or substantial portions include the original attribution.



---

2. GNU Affero General Public License v3 (AGPL-3.0) with a Non-Commercial Clause

While AGPL-3.0 is more complex than Creative Commons licenses, it’s well-suited for software, especially if it's intended for web services or network-based use. AGPL requires that anyone who modifies and publicly uses the software must make their modifications available under the same terms.

To adapt AGPL with non-commercial restrictions:

Use the standard AGPL-3.0 license text (available here) and add a specific Non-Commercial Clause stating that commercial use is prohibited unless a separate license is obtained.


How to Use It:

Include the AGPL-3.0 license text with an added clause at the top, such as:

This software is licensed under the GNU Affero General Public License v3 (AGPL-3.0).
**Non-Commercial Use Only**: This software may not be used for commercial purposes without explicit permission.

Add a note in the README to clarify the non-commercial restriction.



---

Both of these options offer robust, community-recognized frameworks for non-commercial licenses, with clear and enforceable terms.

**Comment by prem-k-r** [comment]
Link
1.https://creativecommons.org/licenses/by-nc/4.0/legalcode
2. https://www.gnu.org/licenses/agpl-3.0.en.html

**Comment by itz-rj-here** [comment]
> I don't really know how this things work. I put it in ChatGPT, see what it says: Your modified license text creates a Non-Commercial variant of the MIT License, which restricts the use of the software to non-commercial purposes. However, it’s important to note that this version isn’t officially recognized as the MIT License because MIT itself does not allow restricting commercial use in its standard terms. Here’s a breakdown of considerations:
> 
> 1. Custom License: By adding a "Non-Commercial Use Only" restriction, this license becomes a custom license. You may wish to clearly state it as something like "MIT License (Non-Commercial)" or simply "Non-Commercial License" to avoid any legal confusion, as users may assume that the MIT License allows commercial use by default.
> 2. Compatibility and Community Acceptance: The open-source community generally prefers licenses without restrictions on commercial use, like MIT or Apache. If you intend to submit your project to certain open-source directories or repositories, they might not accept this modified version since it doesn’t adhere to the Open Source Initiative’s definition.
> 3. Alternative Licenses: If a non-commercial license is essential, consider recognized options such as:
> 
> Creative Commons Non-Commercial Licenses (CC BY-NC): Though more common in content (e.g., documentation), it’s well-suited for non-commercial use and is widely understood.
> 
> GNU Affero General Public License (AGPL) or MPL with Non-Commercial Clauses: These are also restrictive, but you can consider variations based on the level of restriction needed.
> 
> Your license text itself appears legally sound if your goal is to allow non-commercial use only. Just keep in mind that creating a custom license may reduce compatibility with other open-source projects or platforms.

Hmm. I can understand. Ok let me research little bit for on it.

**Comment by itz-rj-here** [comment]
> Link 1.https://creativecommons.org/licenses/by-nc/4.0/legalcode 2. https://www.gnu.org/licenses/agpl-3.0.en.html

Great thanks. Let me see this.

**Comment by itz-rj-here** [comment]
Checked by the ChatGPT now for the official recognition. Here is the reply from the ChatGPT:

Yes, the license text you've provided now retains the official GNU General Public License v3.0 (GPL-3.0) status while allowing you to include your specific terms in a separate section. Here’s a summary of how this works:

### Components of Your License

1. **Official GPL-3.0 Language**:
   - The first part of your license remains the official GPL-3.0 text, which grants users the freedom to use, modify, and redistribute the software. This part is key to maintaining its status as GPL-3.0.

2. **Warranty Disclaimer**:
   - The disclaimer about warranty is also part of the GPL-3.0 license, ensuring users are aware that the software is provided without guarantees.

3. **Custom Additional Information**:
   - The "Additional Information" section clearly states your specific restrictions and guidelines about commercial use and bug reporting. This is separate from the license terms, which means it does not alter the fundamental freedoms granted by the GPL-3.0.

### Conclusion

- **Officially Recognized**: Because you’ve included the unaltered GPL-3.0 text and separated your additional conditions, the license is now officially recognized as GPL-3.0. Your custom terms do not change the original licensing agreement and simply provide context for how you wish users to handle the software.

### Recommendation

Make sure to clearly communicate in your project documentation that while the software is licensed under GPL-3.0, the additional information provides your preferences regarding usage and support. This transparency will help users understand their rights and responsibilities concerning your project. 

By maintaining this structure, you effectively combine the robust framework of the GPL-3.0 with your specific needs, ensuring both legal clarity and practical guidance for users of your software.

**Comment by itz-rj-here** [comment]
@prem-k-r

**Comment by itz-rj-here** [comment]
@prem-k-r

**Comment by prem-k-r** [comment]
delete line 17: We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your extentions, too.

**Comment by prem-k-r** [comment]
Maybe add at top:

This software is licensed under the GNU Affero General Public License v3 (AGPL-3.0).

**Non-Commercial Use Only**: This software may not be used for commercial purposes without explicit permission from the copyright holder.

---

**Comment by itz-rj-here** [comment]
> Maybe add at top:
> 
> This software is licensed under the GNU Affero General Public License v3 (AGPL-3.0).
> 
> **Non-Commercial Use Only**: This software may not be used for commercial purposes without explicit permission from the copyright holder.

First of all it's a extention not a software.
Second of all i need to check if adding this additional info will break the license format.

**Comment by prem-k-r** [comment]
chatgpt:

Why CC BY-NC 4.0 Is a Good Fit:
Simplicity: The CC BY-NC 4.0 license is straightforward and familiar, especially for projects that emphasize UI design and user personalization, as in a browser extension inspired by Google’s Material You design. This license is easy for users to understand and readily recognizable.

Non-Commercial Requirement: Since your extension is a tool for personalizing the browsing experience and doesn’t involve backend server components or network interactions, the simplicity of CC BY-NC 4.0 is ideal. This license restricts commercial use, ensuring the extension can’t be sold or used in a commercial setting without permission.

Design-Focused Projects: Many design and UI-focused projects (e.g., themes, templates, media) use Creative Commons licenses, as they allow others to share and adapt the work non-commercially while giving credit. This fits well for projects emphasizing aesthetics, like your Material You-inspired extension.

Compatibility with Browser Extension Distribution Platforms: Most browser extension platforms (like Chrome Web Store or Firefox Add-ons) readily accept extensions under Creative Commons licenses. This will make it easy for others to understand the terms, should they wish to modify or share the extension non-commercially.

**Comment by itz-rj-here** [comment]
> chatgpt:
> 
> Why CC BY-NC 4.0 Is a Good Fit: Simplicity: The CC BY-NC 4.0 license is straightforward and familiar, especially for projects that emphasize UI design and user personalization, as in a browser extension inspired by Google’s Material You design. This license is easy for users to understand and readily recognizable.
> 
> Non-Commercial Requirement: Since your extension is a tool for personalizing the browsing experience and doesn’t involve backend server components or network interactions, the simplicity of CC BY-NC 4.0 is ideal. This license restricts commercial use, ensuring the extension can’t be sold or used in a commercial setting without permission.
> 
> Design-Focused Projects: Many design and UI-focused projects (e.g., themes, templates, media) use Creative Commons licenses, as they allow others to share and adapt the work non-commercially while giving credit. This fits well for projects emphasizing aesthetics, like your Material You-inspired extension.
> 
> Compatibility with Browser Extension Distribution Platforms: Most browser extension platforms (like Chrome Web Store or Firefox Add-ons) readily accept extensions under Creative Commons licenses. This will make it easy for others to understand the terms, should they wish to modify or share the extension non-commercially.

Well i used the gpts recommandation for the license tho.

**Comment by itz-rj-here** [comment]
> > chatgpt:
> > Why CC BY-NC 4.0 Is a Good Fit: Simplicity: The CC BY-NC 4.0 license is straightforward and familiar, especially for projects that emphasize UI design and user personalization, as in a browser extension inspired by Google’s Material You design. This license is easy for users to understand and readily recognizable.
> > Non-Commercial Requirement: Since your extension is a tool for personalizing the browsing experience and doesn’t involve backend server components or network interactions, the simplicity of CC BY-NC 4.0 is ideal. This license restricts commercial use, ensuring the extension can’t be sold or used in a commercial setting without permission.
> > Design-Focused Projects: Many design and UI-focused projects (e.g., themes, templates, media) use Creative Commons licenses, as they allow others to share and adapt the work non-commercially while giving credit. This fits well for projects emphasizing aesthetics, like your Material You-inspired extension.
> > Compatibility with Browser Extension Distribution Platforms: Most browser extension platforms (like Chrome Web Store or Firefox Add-ons) readily accept extensions under Creative Commons licenses. This will make it easy for others to understand the terms, should they wish to modify or share the extension non-commercially.
> 
> Well i used the gpts recommandation for the license tho.

As you say i will look into that too.

**Comment by prem-k-r** [comment]
> > > chatgpt:
> > > Why CC BY-NC 4.0 Is a Good Fit: Simplicity: The CC BY-NC 4.0 license is straightforward and familiar, especially for projects that emphasize UI design and user personalization, as in a browser extension inspired by Google’s Material You design. This license is easy for users to understand and readily recognizable.
> > > Non-Commercial Requirement: Since your extension is a tool for personalizing the browsing experience and doesn’t involve backend server components or network interactions, the simplicity of CC BY-NC 4.0 is ideal. This license restricts commercial use, ensuring the extension can’t be sold or used in a commercial setting without permission.
> > > Design-Focused Projects: Many design and UI-focused projects (e.g., themes, templates, media) use Creative Commons licenses, as they allow others to share and adapt the work non-commercially while giving credit. This fits well for projects emphasizing aesthetics, like your Material You-inspired extension.
> > > Compatibility with Browser Extension Distribution Platforms: Most browser extension platforms (like Chrome Web Store or Firefox Add-ons) readily accept extensions under Creative Commons licenses. This will make it easy for others to understand the terms, should they wish to modify or share the extension non-commercially.
> > 
> > 
> > Well i used the gpts recommandation for the license tho.
> 
> As you say i will look into that too.

If you want I can do it

**Comment by itz-rj-here** [comment]
> > > > chatgpt:
> > > > Why CC BY-NC 4.0 Is a Good Fit: Simplicity: The CC BY-NC 4.0 license is straightforward and familiar, especially for projects that emphasize UI design and user personalization, as in a browser extension inspired by Google’s Material You design. This license is easy for users to understand and readily recognizable.
> > > > Non-Commercial Requirement: Since your extension is a tool for personalizing the browsing experience and doesn’t involve backend server components or network interactions, the simplicity of CC BY-NC 4.0 is ideal. This license restricts commercial use, ensuring the extension can’t be sold or used in a commercial setting without permission.
> > > > Design-Focused Projects: Many design and UI-focused projects (e.g., themes, templates, media) use Creative Commons licenses, as they allow others to share and adapt the work non-commercially while giving credit. This fits well for projects emphasizing aesthetics, like your Material You-inspired extension.
> > > > Compatibility with Browser Extension Distribution Platforms: Most browser extension platforms (like Chrome Web Store or Firefox Add-ons) readily accept extensions under Creative Commons licenses. This will make it easy for others to understand the terms, should they wish to modify or share the extension non-commercially.
> > > 
> > > 
> > > Well i used the gpts recommandation for the license tho.
> > 
> > 
> > As you say i will look into that too.
> 
> If you want I can do it

Well there is none here
image

**Comment by prem-k-r** [comment]
wait

**Comment by itz-rj-here** [comment]
> wait

Check first if github supports this license then i will add it.

**Comment by itz-rj-here** [comment]
https://github.com/github/choosealicense.com/issues/33
looks like it supports it but doesn't shows up by default. i will try it tomorrow. im going to sleep now bye.

**Comment by itz-rj-here** [comment]
Let me also mention you that its actually known as [CC0-1.0 license](https://github.com/Gibberlings3/GitHub-Templates?tab=CC0-1.0-1-ov-file#CC0-1.0-1-ov-file). you can see this too you will understand everything.

**Comment by prem-k-r** [comment]
> [github/choosealicense.com#33](https://github.com/github/choosealicense.com/issues/33) looks like it supports it but doesn't shows up by default. i will try it tomorrow. im going to sleep now bye.

just added #148

**Comment by prem-k-r** [comment]
> > > [github/choosealicense.com#33](https://github.com/github/choosealicense.com/issues/33) looks like it supports it but doesn't shows up by default. i will try it tomorrow. im going to sleep now bye.
> > 
> > 
> > just added #148
> 
> see the comments

this is from year 2013, v3.0

**Review by prem-k-r — APPROVED** [review]

**Comment by itz-rj-here** [comment]
Well its not a software its an extention this license needs to be changed. Closing this pr for now. Will create a very fresh pr for the license tomorrow.

**Comment by itz-rj-here** [comment]
https://chatgpt.com/share/672a55f0-1f34-8006-bfda-1495e0c55877

**Comment by ceskyDJ** [comment]
> * **Warranty Disclaimer**: The software is provided "as is," without any warranty. If you encounter any bugs or issues, please report them in our GitHub repository, and we will do our best to address them.
> * **Commercial Use**: Please note that this software cannot be sold or used for commercial purposes. This is a specific restriction I’ve added to ensure the project remains free for everyone.
> * **Modified Versions**: While we encourage contributions and modifications, please understand that we cannot provide support for issues arising from modified versions of the software that are not derived from the original code.

So, you want something like this:

**Permissions:**
- Modification
- Private Use

**Conditions:**
- License and copyright notice

**Limitations:**
- Liability
- Warranty
- Commercial Use

You can see a list of casual licenses here: https://choosealicense.com/licenses/.

By the way, why do you want to prohibit commercial use?

**Comment by itz-rj-here** [comment]
> > * **Warranty Disclaimer**: The software is provided "as is," without any warranty. If you encounter any bugs or issues, please report them in our GitHub repository, and we will do our best to address them.
> > * **Commercial Use**: Please note that this software cannot be sold or used for commercial purposes. This is a specific restriction I’ve added to ensure the project remains free for everyone.
> > * **Modified Versions**: While we encourage contributions and modifications, please understand that we cannot provide support for issues arising from modified versions of the software that are not derived from the original code.
> 
> So, you want something like this:
> 
> **Permissions:**
> - Modification
> - Private Use
> 
> **Conditions:**
> - License and copyright notice
> 
> **Limitations:**
> - Liability
> - Warranty
> - Commercial Use
> 
> You can see a list of casual licenses here: https://choosealicense.com/licenses/.
> 
> By the way, why do you want to prohibit commercial use?

Cause no one can use it for making money. Commercial use means anyone can use this to make profit. Thats way.

**Comment by itz-rj-here** [comment]
> Why do you think this is not a software? Even Google thinks it's software: https://developer.chrome.com/docs/extensions/mv2/overview.
> 
> Of course, the complexity of the extension isn't very big, but it's still software. [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/software) defines software as:
> > the [instructions](https://dictionary.cambridge.org/dictionary/english/instructions) that [control](https://dictionary.cambridge.org/dictionary/english/control) what a [computer](https://dictionary.cambridge.org/dictionary/english/computer) does

It’s completely on XengShi. If he thinks we should change it extention then we will and if he thinks it should be a software then we will change it. 
But for now, as all of your recommandation and ideas i will create a proper license for the project. When i come from school. Thanks for the ideas tho.

**Comment by ceskyDJ** [comment]
> It’s entirely on XengShi. If he thinks we should change the extension, then we will, and if he says it should be software, then we will change it.

I think it's just law stuff, but I don't have enough time to deep dive into it and link law sources for my argument. So, yeah, it's finally up to XengShi.

> But for now, as per all of the recommendations and ideas, I will create a proper license for the project. When I come home from school. Thanks for the ideas tho.

Just be aware that you are not a lawyer (or aren't you?), so it's always the best option to use one of the licenses approved by time and professional lawyers.

I provide some notes from my experience. Feel free to make your own decisions based on your judgment.

**Comment by ceskyDJ** [comment]
> Cause no one can use it to make money. Commercial use means anyone can use this to make a profit—that way.

It's tough to enforce this. So, most open-source projects use some copyleft license in this case and don't care. As the source codes must always be public, users can get the software for free. It makes the software effectively free all the time, at least for educated users. But of course, you can put anything to your license if it's in the borders of the law.

**Comment by itz-rj-here** [comment]
> > Cause no one can use it to make money. Commercial use means anyone can use this to make a profit—that way.
> 
> It's tough to enforce this. So, most open-source projects use some copyleft license in this case and don't care. As the source codes must always be public, users can get the software for free. It makes the software effectively free all the time, at least for educated users. But of course, you can put anything to your license if it's in the borders of the law.

I think we need to open a discussion on this.

**Pull request closed without merging**
