### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
- corrected size and icon of meta ai + added its translation
- removed color palette hover text + removed its translation
- removed unnecessary comment from other lang and changed menu width for french
- hindi translation update
- added french in readme
- update github link in feedback
- Remove leading zero from hours in 12-hour format for digital clock in english too
- added missing .dark-theme and hover color change for upload and random wallpaper for dark theme
- changed firefox scrollbar width auto to thin
- save button scaling on click
- github shortcut icon's white color opacity increased
- readjusted spacing between lang, theme, wp, reset..
image

- Moved try statement, and switched to coordinate fetching instead of city name from ipinfo (Hide whitespaces to see this change clearly)

## Related Issues
#304 (fix: dark theme colors persisting even after theme change)
so page reload hint is not needed anymore

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
done, please review..

**Comment by itz-rj-here** [comment]
Also i don't see the menu settings icon is not perfectly centered. :(

**Comment by prem-k-r** [comment]
> I can see all ok but what about the shortcuts icon alignment? image

what happened?

**Comment by prem-k-r** [comment]
> Also i don't see the menu settings icon is not perfectly centered. :(

I rechecked in all browsers.. nothing out of order for me

**Comment by itz-rj-here** [comment]
image
Look the sides of the circle you will understand.

**Comment by XengShi** [comment]
Please fix the conflicts and remove shadows code for texts because I have added solid background....

**Comment by prem-k-r** [comment]
> Please fix the conflicts and remove shadows code for texts because I have added solid background....

ok.

for analog clock.. two-lined usertext overlapping a bit.
image

do you want bg for everytime.. I mean even for no wallpaper scenario?

**Comment by XengShi** [comment]
> > Please fix the conflicts and remove shadows code for texts because I have added solid background....
> 
> ok.
> 
> for analog clock.. two-lined usertext overlapping a bit.
> image
> 
> do you want bg for everytime.. I mean even for no wallpaper scenario?

I will fix that,
For no wallpapar solid background can be removed, if you want you are free to remove

**Comment by prem-k-r** [comment]
Done, please check

if has wallpaper then solid background else not

**Pull request merged**
