### PR TITLE
Update script.js for Czech date formatting

### PR DESCRIPTION
**Pull request by prem12321kumar**

### CODE REVIEW

**Comment by prem12321kumar** [comment]
+ #99

**Comment by prem12321kumar** [comment]
@XengShi it shows regional date format of Czech, example 
Pondělí, 21. října
Monday, 21. october
instead of default English one: Mon, Oct 21

**Comment by ceskyDJ** [comment]
How is this going?

**Comment by prem12321kumar** [comment]
> How is this going?

In #107 
duplicate, so closed this one

**Comment by ceskyDJ** [comment]
Oh, I see. Thanks for explanation.

**Pull request closed without merging**
