### PR TITLE
CC BY-4.0 License

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by itz-rj-here** [comment]
image
GitHub couldn't detect the license. @prem-k-r

**Comment by itz-rj-here** [comment]
If you think we should use this for sure then your good to go.

**Comment by itz-rj-here** [comment]
Although, it counts as a custom license.

**Comment by itz-rj-here** [comment]
But i would recommand to check it more deeply. so it can detect the license. If it detects the license the name will be changed to CC BY-NC 4.0.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type
Check this first then do the changes lastly i recommand.

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
CC BY-NC 4.0 is not supported in the GitHub repo. for more info [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type)

**Comment by prem-k-r** [comment]
yes, you are right. 
so we can go for either GPL-3.0 license or CC-BY-4.0

**Comment by itz-rj-here** [comment]
Still have issues

**Comment by itz-rj-here** [comment]
Why you don't get some knowledge from other repo's
https://github.com/santisoler/cc-licenses/blob/main/LICENSE
see this.

**Comment by prem-k-r** [comment]
nah, its fine, gonna close all this..

**Comment by itz-rj-here** [comment]
Fine.

**Comment by itz-rj-here** [comment]
I can understand what you are requesting i will do that tomorrow don't worry tho.

**Comment by prem-k-r** [comment]
GPL-3.0 is good to go na, as it is detected by Github?
lets just go with it if XengShi agrees

**Pull request closed without merging**
