### PR TITLE
Hide Scrollbar When Shortcuts Overflow

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by itz-rj-here** [comment]
Before
image

After
image

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
No rolling animation?
image

**Comment by prem-k-r** [comment]
> No rolling animation? image

XengShi did. tbh I like this one. last one tilt 10° 😵

**Comment by itz-rj-here** [comment]
> > No rolling animation? image
> 
> XengShi did. tbh I like this one. last one tilt 10° 😵

Agreed. It's actually better than the old one.

**Comment by prem-k-r** [comment]
> Before [image]
> 
> After [image]

It didn't look good to me, plus it was visible in the menu too. Also, clicking on 'AI Tools' hid the scrollbar and shifted the entire screen.

**Comment by itz-rj-here** [comment]
@prem-k-r can you now do the language dropdown thingy.

**Comment by prem-k-r** [comment]
> @prem-k-r can you now do the language dropdown thingy.

ok

**Comment by itz-rj-here** [comment]
> > Before [image]
> > After [image]
> 
> It didn't look good to me, plus it was visible in the menu too. Also, clicking on 'AI Tools' hid the scrollbar and shifted the entire screen.

Saw that. Just added the ss for @XengShi.

**Comment by XengShi** [comment]
> > > Before [image]
> > > After [image]
> > 
> > It didn't look good to me, plus it was visible in the menu too. Also, clicking on 'AI Tools' hid the scrollbar and shifted the entire screen.
> 
> Saw that. Just added the ss for @XengShi.

Thanks

**Comment by XengShi** [comment]
@prem-k-r @itz-rj-here 
I hope you test the extension on Chrome and Firefox before submitting a pull request.

Before merging any PR, I personally test the extension on both browsers. If you’re already testing it beforehand, please let me know so I can review and merge your changes more quickly.

**Comment by prem-k-r** [comment]
I have tested this one on chrome, edge, firefox and brave

**Comment by prem-k-r** [comment]
> @prem-k-r @itz-rj-here I hope you test the extension on Chrome and Firefox before submitting a pull request.
> 
> Before merging any PR, I personally test the extension on both browsers. If you’re already testing it beforehand, please let me know so I can review and merge your changes more quickly.

ok noted

**Comment by itz-rj-here** [comment]
> @prem-k-r @itz-rj-here 
> I hope you test the extension on Chrome and Firefox before submitting a pull request.
> 
> Before merging any PR, I personally test the extension on both browsers. If you’re already testing it beforehand, please let me know so I can review and merge your changes more quickly.
> 

Uhhh. For now i just tested it on chrome. Idk about the firefox. But as you said i will do that from now on.

**Comment by itz-rj-here** [comment]
@prem-k-r remind me to mention when the language thingy is done.

**Comment by XengShi** [comment]
> > @prem-k-r @itz-rj-here 
> > I hope you test the extension on Chrome and Firefox before submitting a pull request.
> > 
> > Before merging any PR, I personally test the extension on both browsers. If you’re already testing it beforehand, please let me know so I can review and merge your changes more quickly.
> > 
> 
> Uhhh. For now i just tested it on chrome. Idk about the firefox. But as you said i will do that from now on.


Yup, because some visual changes look different in Firefox 🙃

**Comment by itz-rj-here** [comment]
> > > @prem-k-r @itz-rj-here 
> > > I hope you test the extension on Chrome and Firefox before submitting a pull request.
> > > 
> > > Before merging any PR, I personally test the extension on both browsers. If you’re already testing it beforehand, please let me know so I can review and merge your changes more quickly.
> > > 
> > 
> > Uhhh. For now i just tested it on chrome. Idk about the firefox. But as you said i will do that from now on.
> 
> 
> Yup, because some visual changes look different in Firefox 🙃

Yup cuz it's not chromium based 🙂

**Pull request merged**
