### PR TITLE
Centered Github and Feedback tile

### PR DESCRIPTION
**Pull request by prem-k-r**
image
image
to
image
image

after centering
In some languages with longer text of Feedback, fixed display
image

### CODE REVIEW

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
The text aren't properly fitted on the box. The older changes looks good for me.

**Comment by prem-k-r** [comment]
> The text aren't properly fitted on the box. The older changes looks good for me.

Which ones? Screenshot please

**Comment by itz-rj-here** [comment]
image

The upper image looks good to me. But the 2nd image doesn't looks good to me cause there is no gap at the right side of the text. :(

**Comment by itz-rj-here** [comment]
I will recommand to keep some gap between the texts and the icons.

**Comment by prem-k-r** [comment]
> image
> 
> The upper image looks good to me. But the 2nd image doesn't looks good to me cause there is no gap at the right side of the text. :(

Lol first image is what currently they are as for feedback tile. XengShi probably don't like it (text in 2 line), so no changes for five languages which have longer translation for feedback

**Comment by prem-k-r** [comment]
For 'idn', 'ja', 'ru', 'tr', 'uz'

**Comment by XengShi** [comment]
> > image
> > 
> > The upper image looks good to me. But the 2nd image doesn't looks good to me cause there is no gap at the right side of the text. :(
> 
> Lol first image is what currently they are as for feedback tile. XengShi probably don't like it (text in 2 line), so no changes for five languages which have longer translation for feedback 

Yes, I really don't like text in two lines, also in feels like temperature

**Comment by prem-k-r** [comment]
@itz-rj-here please check now, I think it's better now
image
image
image
image
image

**Comment by itz-rj-here** [comment]
> @itz-rj-here please check now, I think it's better now image image image image image

Better than before..

**Comment by XengShi** [comment]
Sorry but I didn't like the center things 🙃🫠

**Comment by prem-k-r** [comment]
> Sorry but I didn't like the center things 🙃🫠

np, just close the PR
it is more noticable for larger larger menu width
image

**Comment by prem-k-r** [comment]
> > image
> > The upper image looks good to me. But the 2nd image doesn't looks good to me cause there is no gap at the right side of the text. :(
> 
> Lol second image is what currently they are as for feedback tile. XengShi probably don't like it (text in 2 line), so no changes for five languages which have longer translation for feedback

**Pull request closed without merging**
