### PR TITLE
Added Claude to AI tools

### PR DESCRIPTION
**Pull request by prem-k-r**
image

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]

**Comment by prem-k-r** [comment]
+Removed text shadow delay

**Comment by prem-k-r** [comment]
image
image


uneven padding, should we change it to
image
@XengShi?

**Comment by prem-k-r** [comment]
@XengShi please review, this is a quick one

**Comment by XengShi** [comment]
> @XengShi please review, this is a quick one

I think there should be an option to which AI tools users want to show.

Since most of them are useless, for example I mostly use chatgpt only. But if there are so many, it causes the issue of responsiveness

**Comment by itz-rj-here** [comment]
> > @XengShi please review, this is a quick one
> 
> I think there should be an option to which AI tools users want to show.
> 
> Since most of them are useless, for example I mostly use chatgpt only. But if there are so many, it causes the issue of responsiveness

Yeah we need to add something like shortcuts menu thingy

**Comment by prem-k-r** [comment]
Yeah fair enough.. need extra page for both Search engine and AI-Tools..

This can be last one.. Since it is quite popular and still okish in 16:9 screen at font size 16.

**Comment by prem-k-r** [comment]
Responsiveness can be managed to most extend by #227

**Pull request closed without merging**
