### PR TITLE
feat: add new language vietnamese

### PR DESCRIPTION
**Pull request by diepdo1810**
## TODO
- [x] done

### CODE REVIEW

**Review by prem12321kumar — APPROVED** [review]

**Comment by prem12321kumar** [comment]
Just need to add in html too

**Comment by diepdo1810** [comment]
> Just need to add in html too

done.

**Review by prem12321kumar — COMMENTED** [review]
is it not tiếng Việt?

**Comment by prem12321kumar** [comment]
Also I've recently changed "Enable/Disable" to "Show/Hide" for shortcuts and AI tools, since it determines whether they are visible or not.
For the digital clock and search suggestions, "Enable/Disable" is still there as it affects their functionality or availability, not just their visibility.

can you check if it needed to change in Vietnamese or is it already natural.

**Review by prem12321kumar — APPROVED** [review]

**Comment by diepdo1810** [comment]
> can you check if it needed to change in Vietnamese or is it already natural.

Yes, I checked. I think it is necessary because sometimes people in my country prefer local language.

> is it not tiếng Việt?

Thanks for reminding.

**Comment by prem12321kumar** [comment]
> > can you check if it needed to change in Vietnamese or is it already natural.
> 
> Yes, I checked. I think it is necessary because sometimes people in my country prefer local language.
> 

Natural I meant in the sense there's no need to follow the English translation word-for-word, but what sounds perfect and natural in local region.

**Comment by diepdo1810** [comment]
> > > can you check if it needed to change in Vietnamese or is it already natural.
> > 
> > 
> > Yes, I checked. I think it is necessary because sometimes people in my country prefer local language.
> 
> Natural I meant in the sense there's no need to follow the English translation word-for-word, but what sounds perfect and natural in local region.

Thank you. i appreciate it. But no problem

**Review by itz-rj-here — APPROVED** [review]

**Comment by diepdo1810** [comment]
Could this PR be labeled as hacktoberfest-accepted. Thanks!

**Comment by prem-k-r** [comment]
I would say to add topics, but it's upto @XengShi 
Repo > About > Gear icon(edit) > Topics

material-you new-tab material-design chrome chrome-extension firefox-addon edge-extension safari-extension brave-extension clock weather-widget search search-suggestions bookmark shortcut theme dark-theme multi-language javascript hacktoberfest

**Comment by prem-k-r** [comment]
> I would suggest adding topics, but it's up to @XengShi Repo > About > Gear icon(edit) > Topics
> 
> material-you new-tab material-design home-page chrome chrome-extension firefox-addon edge-extension safari-extension brave-extension ui-ux clock weather-widget search search-suggestions bookmark shortcut theme dark-theme multilingual i18n l10n javascript hacktoberfest

@XengShi, your thoughts on this?

**Comment by itz-rj-here** [comment]
> I would suggest adding topics, but it's up to @XengShi Repo > About > Gear icon(edit) > Topics
> 
> material-you new-tab material-design home-page chrome chrome-extension firefox-addon edge-extension safari-extension brave-extension ui-ux clock weather-widget search search-suggestions bookmark shortcut theme dark-theme multilingual i18n l10n javascript hacktoberfest

Can you explain what is this? also talking on the merged pr. thats kinda odd.

**Comment by itz-rj-here** [comment]
Ohh i can tell him about that.

**Comment by prem-k-r** [comment]
added nice!
but there is a typo @XengShi 

image

**Pull request merged**
