### PR TITLE
l10n: Update Czech translation

### PR DESCRIPTION
**Pull request by ceskyDJ**
## Description
This pull request brings updates of Czech translation so that new strings will be available for Czech-speaking people.

## Related Issues
- Issue #195 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by ceskyDJ** [comment]
Waiting for @prem-k-r's answers under https://github.com/XengShi/materialYouNewTab/discussions/195#discussioncomment-11650679.

**Comment by prem-k-r** [comment]
please refer https://github.com/XengShi/materialYouNewTab/discussions/195#discussioncomment-11659743

**Comment by ceskyDJ** [comment]
> please refer [#195 (comment)](https://github.com/XengShi/materialYouNewTab/discussions/195#discussioncomment-11659743)

Hmm, interesting. What should I do with it? Can we merge this before #195?

**Comment by prem-k-r** [comment]
I’m not sure, let’s leave it to @XengShi 
#357 has been open for 3 days. Conflicts have been resolved a few times, any changes in language.js are likely to cause new conflicts. It might be easier to update again after the merge of #357  than fixing conflict.

**Comment by ceskyDJ** [comment]
Ok, so I'll wait for @XengShi's decision.

**Comment by prem-k-r** [comment]
@ceskyDJ please reapply the changes here 
https://github.com/XengShi/materialYouNewTab/blob/main/locales/cs.js

**Comment by ceskyDJ** [comment]
> @ceskyDJ please reapply the changes here 
> https://github.com/XengShi/materialYouNewTab/blob/main/locales/cs.js

Ok, thanks for noticing.

**Comment by ceskyDJ** [comment]
@prem-k-r, I've updated it. Could you look at it, please? I also reformatted the Czech language translation file, as its formatting was a bit weird.

**Review by itz-rj-here — APPROVED** [review]

**Comment by ceskyDJ** [comment]
Thanks, @itz-rj-here! @XengShi, can we merge it?

**Comment by itz-rj-here** [comment]
> Thanks, @itz-rj-here! @XengShi, can we merge it?

He is maybe sleeping. Np. He will merge this soon.

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
Yep all good thanks.
Btw, there is a new alert 
`"UnsupportedBrowser": "Bookmarks are not supported in your browser",`

**Comment by ceskyDJ** [comment]
> Yep all good thanks.
> Btw, there is a new alert 
> `"UnsupportedBrowser": "Bookmarks are not supported in your browser",`

Thanks for merging! I'll look at the new string for translation today.

**Pull request merged**
