### PR TITLE
Added a small animation for the clock and the menu bar exit button.

### PR DESCRIPTION
**Pull request by kerogs**
- The clock hands will be animated when the time is loaded.
- The menu bar exit button has a slightly smoother animation than before.

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]
Perfect

**Comment by itz-rj-here** [comment]
@XengShi You can merge this pull to your repository. It works fine. It adds an animation to the clock and when we exit the menu bar.

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Can you kindly resolve the conflicts...

**Comment by XengShi** [comment]
[Screencast from 2024-10-10 20-52-54.webm](https://github.com/user-attachments/assets/89bd323e-6282-4874-8cfe-c2c6b2d8ae32)
Kindly fix these issue:

- When second dot completes it cycle it rotates once in opposite direction
- Add some margin top for close button &  make it perfect circle

**Comment by kerogs** [comment]
> [Screencast from 2024-10-10 20-52-54.webm](https://github.com/user-attachments/assets/89bd323e-6282-4874-8cfe-c2c6b2d8ae32) Kindly fix these issue:
> 
>     * When second dot completes it cycle it rotates once in opposite direction
> 
>     * Add some margin top for close button &  make it perfect circle

- Corrected the rotation of the second dot to prevent it from rotating in the opposite direction after completing its cycle.
- Added top margin to the close button and adjusted its styling to ensure it is a perfect circle.

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Still the branch has conflicts...

**Comment by itz-rj-here** [comment]
@kerogs can you fix this conflicts one more time? So I can review it and ask @XengShi to check the code and merge the pull.

**Comment by kerogs** [comment]
The conflicts have been resolved

**Comment by itz-rj-here** [comment]
@XengShi Can you kindly check this and merge it to the repo. Please.

**Comment by itz-rj-here** [comment]
> The conflicts have been resolved

Thank you.

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
https://screenrec.com/share/kYws8cfAtO

**Comment by XengShi** [comment]
@kerogs Clock has still some weird animations issues 
https://github.com/user-attachments/assets/c9211ca8-bd66-4497-9718-6e55e2307c46

**Comment by itz-rj-here** [comment]
@kerogs

**Comment by itz-rj-here** [comment]
Looks like it happens when keeping the tab open for too long and using other tab. when going back to the home tab something happens.

**Comment by kerogs** [comment]
I just tried with different browsers, it happens on browsers like chrome or edge from what I see. I'm on Firefox and I don't have any problems.

So the problem does indeed stem from what @itz-rj-here said.

To ensure that the animation is smooth and that the hands don't move backwards, I had to add up the degrees. 
It's not possible (or at least I haven't figured out how) to make the hands go from 280 degrees to 0 degrees correctly with the animation. This would teleport the hands and break the animation.

The problem is that browsers like chrome and edge stop the tab and reload it directly where it's supposed to be. This makes the animation play. If you return to the tab after a while, it will add the number of degrees from where it should be. And since the JS code adds the degrees, it will play an animation (with css) because it will go from 180 degrees to 400 degrees, for example. But I don't know how to make browsers like google and edge not play the CSS animation when you come back to the tab and put the css animation back once the page has added the number of degrees correctly...

**Comment by kerogs** [comment]
I did some research and the way I found is this: 

You need to add code to script.js that will disable the animation for 100 ms after returning to a tab, temporarily disabling the animation so that the browser doesn't rotate the hands too quickly.
```js
window.addEventListener("focus", function() {
    document.querySelector(".clock").classList.add("stop");
    setTimeout(function() {
        document.querySelector(".clock").classList.remove("stop");
    }, 100);
});
```

and add a class in style.css that will disable the animation. I've tried it on chrome and edge and it works.
```css
.clock.stop #hour,
.clock.stop #minute,
.clock.stop #second {
    transition: unset !important;
}
```

**Comment by itz-rj-here** [comment]
I have classes to attend. Talk to @Minuga-RC about it. I think he had managed to fix the clock but still.

**Comment by Minuga-RC** [comment]
> It's not possible (or at least I haven't figured out how) to make the hands go from 280 degrees to 0 degrees correctly with the animation. This would teleport the hands and break the animation.

I had the same problem so what I did is if the rotation is 0deg i will turn off animations and manually set the rotation to 360deg and it seems to work until #75 happened

**Pull request merged**
