### PR TITLE
Fixed Motivational Quotes Toggle

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
- Fixed the Motivational Quotes Toggle
- Made the Motivational Quotes appear by default

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
Loaded it like User Text
@prem-k-r you can review, it's workin on mine

**Review by prem-k-r — APPROVED** [review]

**Review by itz-rj-here — APPROVED** [review]
The codes looks good. Great work.

**Comment by prem-k-r** [comment]
When toggle is off, does this only hides it or stop fetching quotes also?

**Comment by XengShi** [comment]
> When toggle is off, does this only hides it or stop fetching quotes also?

@Thunder-Blaze please fix that if you haven't already. fetching quotes function should only run when the quotes Toggle is enabled.

**Comment by Thunder-Blaze** [comment]
Ahh I missed the notif, gimme a min

**Comment by Thunder-Blaze** [comment]
@prem-k-r check now

**Pull request merged**
