### PR TITLE
Update Chrome store branch wrt main

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by prem-k-r** [comment]
done guys, @XengShi @Thunder-Blaze @itz-rj-here please review

**Comment by prem-k-r** [comment]
image
got only this issue, rest are fine

**Comment by itz-rj-here** [comment]
> image got only this issue, rest are fine

@Thunder-Blaze can check that.
I can check the other items...

**Comment by itz-rj-here** [comment]
But first let me analyze the language thingy first then.
@prem-k-r can you tell XengShi to give us a role to maintain the issues. Like labeling those with bug enchantment and others. please?..

**Comment by prem-k-r** [comment]
> image got only this issue, rest are fine

no such problem in main branch?

**Comment by itz-rj-here** [comment]
> > image got only this issue, rest are fine
> 
> no such problem in main branch?

no

**Comment by prem-k-r** [comment]
> But first let me analyze the language thingy first then. @prem-k-r can you tell XengShi to give us a role to maintain the issues. Like labeling those with bug enchantment and others. please?..

well that's upto him lol

**Comment by prem-k-r** [comment]
image
This is in the extension error logs.. no problem with any functionality.. 
probably only for the first time, but why lol..
@Thunder-Blaze any suggestion

**Comment by Thunder-Blaze** [comment]
> > image got only this issue, rest are fine
> 
> no such problem in main branch?

nope, I increased the specificity in the latest Bookmark icon fix PR

**Comment by Thunder-Blaze** [comment]
> image This is in the extension error logs.. no problem with any functionality.. probably only for the first time, but why lol.. @Thunder-Blaze any suggestion

Either we switch to console.log
As console.error will produce an error (as It tells there is error)

**Comment by itz-rj-here** [comment]
> > But first let me analyze the language thingy first then. @prem-k-r can you tell XengShi to give us a role to maintain the issues. Like labeling those with bug enchantment and others. please?..
> 
> well that's upto him lol

He doesn't know that much about the github modifications and settings. Mybe tell him in his tg. It will be better.

**Comment by prem-k-r** [comment]
> > > But first let me analyze the language thingy first then. @prem-k-r can you tell XengShi to give us a role to maintain the issues. Like labeling those with bug enchantment and others. please?..
> > 
> > 
> > well that's upto him lol
> 
> He doesn't know that much about the github modifications and settings. Mybe tell him in his tg. It will be better.

I also dont know the process :(

**Comment by itz-rj-here** [comment]
> > > > But first let me analyze the language thingy first then. @prem-k-r can you tell XengShi to give us a role to maintain the issues. Like labeling those with bug enchantment and others. please?..
> > > 
> > > 
> > > well that's upto him lol
> > 
> > 
> > He doesn't know that much about the github modifications and settings. Mybe tell him in his tg. It will be better.
> 
> I also dont know the process :(

Uhhhhhh. Fine i will tell him to how to do that :)

**Comment by prem-k-r** [comment]
I think all good now

**Comment by prem-k-r** [comment]
Tested on Windows- Chrome, Edge, Brave

**Comment by prem-k-r** [comment]
> @prem-k-r I see no errors except the WeatherAPI function returning Error sometimes because some of the Keys have reached there limit Awesome 👍🏻
> 

yep, wont be problem from 1st jan, now 2/10 apikey working.. so
> 
> btw for future, can we fetch quotes acc to lang (ig we might need to change the API though)?

Iol, I was about to say this.
also, 
image
upon page reload, quote switch from this default to fetched one.. can we stop it.. the visible swapping?

**Comment by itz-rj-here** [comment]
I have a Question as the search suggestion works without the proxy now, do we need that anymore?

**Comment by prem-k-r** [comment]
image

**Comment by itz-rj-here** [comment]
> image

I liked this one.

**Comment by prem-k-r** [comment]
> I have a Question as the search suggestion works without the proxy now, do we need that anymore?

yeah, lets leave it, it wont work on live page and also when opened in live server

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
Works properly with no such an issue....

**Comment by itz-rj-here** [comment]
@prem-k-r on the bookmark section click on grid 2 times and see if you see any difference or issue...

**Comment by Thunder-Blaze** [comment]
yeah it toggles

**Comment by Thunder-Blaze** [comment]
>image upon page reload, quote switch from this default to fetched one.. can we stop it.. the visible swapping?

I guess we can add a loading kind of ui and display the quote when fetching is succesful ?

**Comment by prem-k-r** [comment]
> @prem-k-r on the bookmark section click on grid 2 times and see if you see any difference or issue...

I know.. this is same in the main branch

**Comment by prem-k-r** [comment]
> > image upon page reload, quote switch from this default to fetched one.. can we stop it.. the visible swapping?
> 
> I guess we can add a loading kind of ui and display the quote when fetching is succesful ?

Are you seeing different quotes everytime page reload? Most of the time it's same for me but it still fetches ig. 
If we leave it blank then.. no such quick swapping.. 
Or maybe let's leave it.. when we switch to different api, if needed, then we can take care of it

**Comment by itz-rj-here** [comment]
> > @prem-k-r on the bookmark section click on grid 2 times and see if you see any difference or issue...
> 
> I know.. this is same in the main branch

It looks odd i think it should be fixed.

**Comment by Thunder-Blaze** [comment]
lemme fix ig a min

Yea I also see the same quote most times on reload

**Comment by Thunder-Blaze** [comment]
@prem-k-r fixed, you can check the PR
(should've choosen to keep listcheckbox 😢 had to add 4 extra lines to keep it checked by default)

**Comment by prem-k-r** [comment]
How to enable notification for PR lol?

**Comment by Thunder-Blaze** [comment]
lol same issue here XD

**Comment by itz-rj-here** [comment]
> How to enable notification for PR lol?

image
use this bruh

**Comment by prem-k-r** [comment]
Ah ok, thanks

**Review by Thunder-Blaze — APPROVED** [review]

**Comment by XengShi** [comment]
@prem-k-r @itz-rj-here  @Thunder-Blaze  SHould I upload it now on chrome ?

**Comment by prem-k-r** [comment]
Yeah, let's go

**Comment by Thunder-Blaze** [comment]
Yeah seems good to me 👍🏻

**Comment by itz-rj-here** [comment]
> @prem-k-r @itz-rj-here @Thunder-Blaze SHould I upload it now on chrome ?

Yeah you should actually. As we almost tried to find and analyze all the codes.

**Comment by prem-k-r** [comment]
ah wait @XengShi 
uploaded?

**Comment by itz-rj-here** [comment]
> ah wait @XengShi uploaded?

what happened?

**Comment by XengShi** [comment]
> ah wait @XengShi 
> uploaded?

What happened

**Comment by prem-k-r** [comment]
something wrong with Grd and List toggle of bookmark
on new tab load selected on grid but showing list view
when one opens a new tab, it is highlighted on grid but its shows list, click list still list, clid gridnow it grid

**Comment by Thunder-Blaze** [comment]
Oh shit I never coded the part to save the toggle after click ☠️
This is why I suck at finding errors 😞 

Gimme a min

**Comment by XengShi** [comment]
image
I didn't uploaded yet, if you have time fix the issue I will wait. they need so much justification!

**Comment by itz-rj-here** [comment]
> image I didn't uploaded yet, if you have time fix the issue I will wait. they need so much justification!

Can you check the tg pls

**Comment by prem-k-r** [comment]
I just pushed a minor change #387, @XengShi you can include this too

**Comment by prem-k-r** [comment]
btw do you want to change this? something meaningful will be better I think
https://github.com/XengShi/materialYouNewTab/discussions/162#discussioncomment-11638655

**Comment by XengShi** [comment]
> btw do you want to change this? something meaningful will be better I think [#162 (reply in thread)](https://github.com/XengShi/materialYouNewTab/discussions/162#discussioncomment-11638655)

You are free to do that.

**Comment by prem-k-r** [comment]
ok thanks

**Comment by prem-k-r** [comment]
no translation :|
image

**Pull request merged**
