### PR TITLE
Display None The Suggestion box when shortcut search toggled

### PR DESCRIPTION
**Pull request by princevora**
- I have Solved the issue of Shortcut search switch.
- Which was not opening when the Suggestion Box for search was visible - open. 

https://github.com/user-attachments/assets/727f4070-c83c-4232-90e4-9e69e51d91cb

### CODE REVIEW

**Comment by prem-k-r** [comment]
Actually, I meant the opposite :)
Disable dropdown click when search suggestion is visible

**Comment by princevora** [comment]
> Actually, I meant the opposite :) Disable dropdown click when search suggestion is visible

Okay done.

**Comment by prem-k-r** [comment]
one more scenario, if dropdown is expanded and user starts writing something, then search suggestion appears above/top of dropdown.
here dropdown should collapse.

**Comment by princevora** [comment]
> one more scenario, if dropdown is expanded and user starts writing something, then search suggestion appears above/top of dropdown. here dropdown should collapse.

i added diffrent instead, it just display none the dropdown when the suggestions appears

**Comment by prem-k-r** [comment]
> > one more scenario, if dropdown is expanded and user starts writing something, then search suggestion appears above/top of dropdown. here dropdown should collapse.
> 
> i added diffrent instead, it just display none the dropdown when the suggestions appears

great

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
@XengShi this seems good to go for merge
This basically
- Disables clicks on the search engine icon when search suggestions are visible.
- Hides the search engine dropdown if it is expanded and search suggestions become visible.

Maybe you can review, and merge it
and then update the extension on the Chrome Web Store

**Comment by XengShi** [comment]
> @XengShi this seems good to go for merge This basically
> 
>     * Disables clicks on the search engine icon when search suggestions are visible.
> 
>     * Hides the search engine dropdown if it is expanded and search suggestions become visible.
> 
> 
> Maybe you can review, and merge it and then update the extension on the Chrome Web Store

Updated the extension on chrome store, but it takes time review is pending.....

**Comment by prem-k-r** [comment]
> Updated the extension on chrome store, but it takes time review is pending.....

oh, that's nice

**Pull request merged**
