### PR TITLE
Update style.css shortcut from bottom to up

### PR DESCRIPTION
**Pull request by Mr-DashginAbdulla**
## Description
Please describe your changes and the purpose of this pull request.

## Related Issues
- Issue #<issue_number>

## Checklist
- [ ] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [ ] I have added necessary tests.
- [ ] The project builds and runs without issues.

### CODE REVIEW

**Comment by Mr-DashginAbdulla** [comment]
shortcut section from bottom to top

**Comment by Thunder-Blaze** [comment]
huh ? why ?
It is good below imo

**Comment by itz-rj-here** [comment]
> huh ? why ?
> wait a min, this isn't even shortcut section

It’s shortcuts container before

**Review by prem-k-r — CHANGES_REQUESTED** [review]
what is this?

**Comment by Thunder-Blaze** [comment]
I also don't get it, top: 0 was already defined above and he ended up removing bottom: 0

**Comment by Thunder-Blaze** [comment]
Also what is this shortcuts container before part for ?
I don't see any point

**Comment by prem-k-r** [comment]
> Also what is this shortcuts container before part for ? I don't see any point

probably not needed.. I'm not that good at css
xengshi can confirm

**Comment by itz-rj-here** [comment]
@XengShi please review it...

**Comment by prem-k-r** [comment]
@Mr-DashginAbdulla this PR doesn't change anything, and the title mentioned is not working at all.

**Comment by itz-rj-here** [comment]
@XengShi

**Pull request closed without merging**
