### PR TITLE
Fixed the buttons if you have a long language,

### PR DESCRIPTION
**Pull request by MestreWalla**
Fixed the length of the buttons if you have a long language, also added a commented code in language.js to change the length of the menu according to the selected language if necessary.

### CODE REVIEW

**Review by itz-rj-here — APPROVED** [review]
Ohh. Thanks. Great work. 👌

**Review by prem-k-r — CHANGES_REQUESTED** [review]
Please delete line 83 in languages.js.

Umm, is quote needed around menuCloseText
If yes, then we have to add quote in other languages too 😅

**Comment by itz-rj-here** [comment]
> Please delete line 83 in languages.js.
> 
> Umm, is quote needed around menuCloseText If yes, then have to add quote in other languages too 😅

In my opinion yeah it should be added. But don't want any explaination, I just told it in my own way. 😅

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Add quotes on all text please if you don't mind.

**Comment by prem-k-r** [comment]
> Fixed the length of the buttons if you have a long language, also added a commented code in language.js to change the length of the menu according to the selected language if necessary.

Thanks for fixing toogle
Maybe width of menu should be increased, long text are cluttering
image

**Comment by MestreWalla** [comment]
a gap on css fix this problem

**Comment by itz-rj-here** [comment]
@prem-k-r is this pr ready to go or some changes are still needed?

**Comment by prem-k-r** [comment]
> @prem-k-r is this pr ready to go or some changes are still needed?

It is ok to go.

but there are some personal suggestion.
- deleting comment in line 83 
- menu is a bit like cluttered, so css fix or increase the width would be better
- Missing translation added, nice
    - But it would be perfect to update some translations adjustments to align with the original English text for accuracy and clarity. (if needed that is, else fine)
- Quote may be added around menuCloseText and morning, afternoon, evening. (not necessary, I/we can add later. for all languages including English lol)

**Comment by prem-k-r** [comment]
> Conflicts!

Fixed

**Pull request merged**
