### PR TITLE
Fix hour hand rotation at 00:00

### LINKED ISSUE #123: Unexpected behavior of the hour hand at 12 am on analog mode
Only when time is 12:00 AM
and pm(?)

https://github.com/user-attachments/assets/414681c5-7512-44c7-8739-6c953ad5988f

### LINKED ISSUE #296: Glitch in 12 AM
In the analog clock when the  time becomes 12 AM the hour dial starts continuously rotating

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
fix 12 am

## Related Issues
Closes #123 
Closes #296 

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
please test

**Review by itz-rj-here — COMMENTED** [review]
Lol I have to wait for 12'o clock for it

**Comment by XengShi** [comment]
> Lol I have to wait for 12'o clock to test it

Set the time to 11:58:30

**Comment by prem-k-r** [comment]
I checked by hard-coding

**Comment by itz-rj-here** [comment]
> > Lol I have to wait for 12'o clock to test it
> 
> Set the time to 11:58:30

Later. I'm doing some other works. :)

**Comment by prem-k-r** [comment]
Btw, there is no transition rn, can add full rotation if you guys like

**Comment by itz-rj-here** [comment]
> Btw, there is no transition rn, can add full rotation if you guys like

like?

**Comment by prem-k-r** [comment]
I'll record screen and share later

**Comment by prem-k-r** [comment]
it's working fine?

**Pull request merged**
