### PR TITLE
Changed color of theme color option in the menu 

### PR DESCRIPTION
**Pull request by prem-k-r**
This PR is subject to review and discussion, please check #140 

Existing:
image

Changed to:
image

### CODE REVIEW

**Comment by XengShi** [comment]
I can't believe, I just (few hours ago) thought about the exact same thing.

**Comment by XengShi** [comment]
image

I am not getting two dark mode buttons

**Comment by prem-k-r** [comment]
> I can't believe, I just (few hours ago) thought about the exact same thing (adding two dark mode options).

What about other color change.. overall it doesn't looks that good as before

**Comment by itz-rj-here** [comment]
Bro i just came from school. My exam went really well.

**Comment by itz-rj-here** [comment]
Literally very well.

**Comment by prem-k-r** [comment]
> image
> 
> I am not getting two dark mode buttons

It is in #130, if I add now, it will show all white when that theme selected

**Comment by itz-rj-here** [comment]
> > image
> > I am not getting two dark mode buttons
> 
> It is in #130, if I add now, it will show all white when that theme selected

I see. let me then update my extention.

**Comment by XengShi** [comment]
> > image
> > I am not getting two dark mode buttons
> 
> It is in #130, if I add now, it will show all white when that theme selected

Okay, having two dark variant full black and greyish would be great, and can you modify yellow theme which currently looks ugly

**Comment by XengShi** [comment]
Old
image

New :
image

**Comment by prem-k-r** [comment]
> > > image
> > > I am not getting two dark mode buttons
> > 
> > 
> > It is in #130, if I add now, it will show all white when that theme selected
> 
> Okay, having two dark variant full black and greyish would be great, and can you modify yellow theme which currently looks ugly


I copied these color codes from theme
I'll change it as you want

**Comment by prem-k-r** [comment]
> Old image
> 
> New : image

Ah wait.. i didn't noticed this.. I didn't mean this.. I'll check.. 
For now let's revert back this PR

**Comment by prem-k-r** [comment]
> Old image
> 
> New : image

that's odd, 
Nothing changed at https://xengshi.github.io/materialYouNewTab/
image

**Comment by itz-rj-here** [comment]
> > Old image
> > New : image
> 
> that's odd, Nothing changed at https://xengshi.github.io/materialYouNewTab/ image

Bruh what you guys are mean to say? The color code you changed is for the menu option only. It will not change the main theme tho. Unless you change something on the theme code.

**Comment by XengShi** [comment]
> > > Old image
> > > New : image
> > 
> > that's odd, Nothing changed at https://xengshi.github.io/materialYouNewTab/ image
> 
> Bruh what you guys are mean to say? The color code you changed is for the menu option only. It will not change the main theme tho. Unless you change something on the theme code.

I just gave him a hint of the new yellow theme by temporarily changing the color using inspect element.

**Comment by prem-k-r** [comment]
> > > > Old image
> > > > New : image
> > > 
> > > 
> > > that's odd, Nothing changed at https://xengshi.github.io/materialYouNewTab/ image
> > 
> > 
> > Bruh what you guys are mean to say? The color code you changed is for the menu option only. It will not change the main theme tho. Unless you change something on the theme code.
> 
> I just gave him a hint of the new yellow theme by temporarily changing the color using inspect element.

Oh lol.. So it was a misunderstanding. 

Btw, what about Cyan theme. This is the only theme I don't like

**Pull request merged**
