### PR TITLE
Light Mode to Dark Mode (refer description)

### PR DESCRIPTION
**Pull request by SmeetPatil**
- Added a new script file to handle my changes and keep the logic separate 
- Basically implementation of light to dark mode for the basic blue color ONLY as of now with contextually accurate UI changes in the menu bar
- Added a container in menu bar with icon and checkbox for this functionality and added required code in css code.  
- Easily undo-able changes.

### CODE REVIEW

**Comment by SmeetPatil** [comment]
Screenshot 2024-11-30 173442

**Comment by itz-rj-here** [comment]
@XengShi It’s a theme related change. I think you should look into it. Thanks.

**Comment by itz-rj-here** [comment]
> Screenshot 2024-11-30 173442
> 

What happens when it’s toggled?

**Comment by SmeetPatil** [comment]
> > Screenshot 2024-11-30 173442
> 
> What happens when it’s toggled?

Yeah here's the video : 

https://github.com/user-attachments/assets/0c37e849-816a-403e-9814-a469f3af3854

**Comment by XengShi** [comment]
> > > Screenshot 2024-11-30 173442
> > 
> > What happens when it’s toggled?
> 
> Yeah here's the video : 
> 
> https://github.com/user-attachments/assets/0c37e849-816a-403e-9814-a469f3af3854
> 
> 

You have done a very good job; we have been wanting to do this for a long time. Thank you for your beautiful work.

**Comment by SmeetPatil** [comment]
> > > > Screenshot 2024-11-30 173442
> > > 
> > > 
> > > What happens when it’s toggled?
> > 
> > 
> > Yeah here's the video :
> > 
> >   
> >     
> >     
> > 
> >     Screen.Recording.2024-11-30.174049.mp4
> 
> You have done a very good job; we have been wanting to do this for a long time. Thank you for your beautiful work.

Thanks a lot, I would love to contribute in this !!!

**Comment by XengShi** [comment]
image

Screenshot from 2024-11-30 18-00-15


Try using the existing dark theme code for dark-colored themes; it would be easier than converting the light theme to a dark one.

**Comment by SmeetPatil** [comment]
> image
> 
> Screenshot from 2024-11-30 18-00-15
> 
> Try using the existing dark theme code for dark-colored themes; it would be easier than converting the light theme to a dark one.

Oh, so use just the one function that changes to dark theme for all the other colors ??

**Comment by XengShi** [comment]
There is a separate code for dark theme in script.js file

-> : 
const resetDarkTheme = () => {
    // Remove the dark theme class
    document.documentElement.classList.remove('dark-theme');

    // Remove the injected dark theme style tag
    if (darkThemeStyleTag) {
        darkThemeStyleTag.remove();
        darkThemeStyleTag = null;
    }

    // Reset inline styles that were applied specifically for dark mode
    const resetElements = [
        "searchQ",
        "searchIconDark",
        "darkFeelsLikeIcon",
        "menuButton",
        "menuCloseButton",
        "closeBtnX"
    ];

    resetElements.forEach((id) => {
        const element = document.getElementById(id);
        if (element) {
            element.removeAttribute('style');
        }
    });...............
........



I meant that if you are modifying this code for a color-based dark theme, it would be easier and better.

As I see, your current theme still has light-colored elements except for the body background, which I guess you will fix later.

But do what works best for you.

**Comment by SmeetPatil** [comment]
> There is a separate code for dark theme in script.js file
> 
> -> : const resetDarkTheme = () => { // Remove the dark theme class document.documentElement.classList.remove('dark-theme');
> 
> ```
> // Remove the injected dark theme style tag
> if (darkThemeStyleTag) {
>     darkThemeStyleTag.remove();
>     darkThemeStyleTag = null;
> }
> 
> // Reset inline styles that were applied specifically for dark mode
> const resetElements = [
>     "searchQ",
>     "searchIconDark",
>     "darkFeelsLikeIcon",
>     "menuButton",
>     "menuCloseButton",
>     "closeBtnX"
> ];
> 
> resetElements.forEach((id) => {
>     const element = document.getElementById(id);
>     if (element) {
>         element.removeAttribute('style');
>     }
> });...............
> ```
> 
> ........
> 
> I meant that if you are modifying this code for a color-based dark theme, it would be easier and better.
> 
> As I see, your current theme still has light-colored elements except for the body background, which I guess you will fix later.
> 
> But do what works best for you.

Yeah I saw that function, I just kept it unmodified so that I could make changes elsewhere, see if they work and then integrate them in the main code. 

Also about the light colored elements, that's intentional for the dark mode to have some contrast. I will change some elements but a mix and match is better in my opinion. The background color is the major factor. 

I will look into your suggestions later, thanks a lot !!

**Review by itz-rj-here — CHANGES_REQUESTED** [review]
Conflicts

**Comment by SmeetPatil** [comment]
> Conflicts

Yeah I saw the wallpaper part. I am currently busy so can't work on it. Do you mind keeping this request up for couple more days ? Thank you.

**Comment by prem-k-r** [comment]
Actually I was think of adding custom theme, there edit starts with selected theme color value, and can be changed to whatever.
Here, we are basically needed to redeclare each color variable again.. we are creating new theme.. instead we can fill remaining 3 spots in palatte with dark themes (Red, Green, Blue based). 
Personally I dont like the UI of this. It's an interesting idea though.

**Comment by SmeetPatil** [comment]
> Actually I was thinking of adding custom theme option, there edit starts with selected theme color value, and can be changed to whatever. Here, we are basically needed to redeclare each color variable again.. we are creating new theme.. instead we can fill remaining 3 spots in palatte with dark themes (Red, Green, Blue based). Personally I dont like the UI of this. It's an interesting idea though.

Yeah fair, I just made this on the fly to show my idea of the dark mode request/idea I had previously proposed. I think we should keep the current dark mode with the ability to change the accent colors only and keep the base dark color the same. The accent can be anything the user chooses with the default being the current monochrome.

**Comment by prem-k-r** [comment]
> Actually I was thinking of adding custom theme option, there edit starts with selected theme color value, and can be changed to whatever. Here, we are basically needed to redeclare each color variable again.. we are creating new theme.. instead we can fill remaining 3 spots in palatte with dark themes (Red, Green, Blue based). Personally I dont like the UI of this. It's an interesting idea though.

As we are not going with this, we should go ahead with the idea of light and dark mode..

Since whole theming stuff is in script.js ... maybe we can avoid extra file
For ui, maybe place the icon below color palette icon? which will be toggle in itself.. when light mode activated, show darkmode icon, aand vice versa..
we can use material you icons
light-mode
night-mode

**Comment by prem-k-r** [comment]
svg path above
image

**Pull request closed without merging**
