### PR TITLE
Grey and Brown Theme

### PR DESCRIPTION
**Pull request by prem-k-r**
image
image
image
image
image

@XengShi Merge or Close whatever you think works best

### CODE REVIEW

**Comment by prem-k-r** [comment]
grey:
image


dark:
image

**Comment by itz-rj-here** [comment]
> grey:
> image
> 
> 
> dark:
> image
> 

Perfect.

**Review by itz-rj-here — APPROVED** [review]

**Comment by itz-rj-here** [comment]
image
image
image
image

Works properly.

**Comment by XengShi** [comment]
The only thing I don't like is Dark text on gray background, and light background behind the Themes, Feels & input fields

**Comment by XengShi** [comment]
But if you guys like it I will merge

**Comment by itz-rj-here** [comment]
> But if you guys like it I will merge

I already liked it. Now for @prem-k-r's answer.

**Comment by prem-k-r** [comment]
It is okish I think , maybe later we can change some elements individually as in dark theme

**Comment by itz-rj-here** [comment]
> It is okish I think , maybe later we can change some elements individually as in dark theme

Agreed.

**Comment by XengShi** [comment]
> It is okish I think , maybe later we can change some elements individually as in dark theme 

You can easily do this by modifying current dark theme code in script.js file

**Comment by itz-rj-here** [comment]
> > It is okish I think , maybe later we can change some elements individually as in dark theme
> 
> You can easily do this by modifying current dark theme code in script.js file

@prem-k-r Can you complete this thing?

**Comment by prem-k-r** [comment]
I'll try

**Comment by prem-k-r** [comment]
Guys, how about brown theme instead? no grey
image
image

**Comment by XengShi** [comment]
> Guys, how about brown theme instead? no grey
> image
> image
> 

We can add more themes without removing gray

**Comment by prem-k-r** [comment]
> > Guys, how about brown theme instead? no grey
> > image
> > image
> 
> We can add more themes without removing gray

Then.. need 4 more lol.. 9 existing, 1 grey, 1 brown,
Well more option to choose theme is better

**Comment by XengShi** [comment]
> > > Guys, how about brown theme instead? no grey
> > > image
> > > image
> > 
> > We can add more themes without removing gray
> 
> Then.. need 4 more lol.. 9 existing, 1 grey, 1 brown,
> Well more option to choose theme is better 

I will handle the UI 🙃

**Comment by itz-rj-here** [comment]
We can add a custom image as a theme too. If someone codes it.

**Comment by prem-k-r** [comment]
> We can add a custom image as a theme too. If someone codes it. :)

Yeah first 14 theme predefined. Last one custom theme.. with 5 color variable: bgcolor, accent, dark, darker, textcolor.. with bgcolor/image option.. 

But need 'someone' 😆

**Comment by itz-rj-here** [comment]
> > We can add a custom image as a theme too. If someone codes it. :)
> 
> Yeah first 14 theme predefined. Last one custom theme.. with 5 color variable: bgcolor, accent, dark, darker, textcolor.. with bgcolor/image option..
> 
> But need 'someone' 😆

Bruhhhhhhhhhhhhh

**Comment by itz-rj-here** [comment]
> image

@prem-k-r Help meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee 😭😭😭😭

**Comment by itz-rj-here** [comment]
> > @prem-k-r Help meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee 😭😭😭😭
> 
> With what?

I don't understand to add a action on opening a menu of the google apps. how to do that?

**Comment by itz-rj-here** [comment]
> > > > @prem-k-r Help meeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee 😭😭😭😭
> > > 
> > > 
> > > With what?
> > 
> > 
> > I don't understand to add a action on opening a menu of the google apps. how to do that?
> 
> Css stuff.. XengShi will be able to help properly

uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh 😭😭😭😭😭😭😭😭

**Comment by prem-k-r** [comment]
Take help from AI Tools button

**Comment by prem-k-r** [comment]
Is it really necessary, Nobody9512 asked for Google account button. Maybe try that only at first. 
Blank Account icon with redirecting link: https://accounts.google.com/SignOutOptions

**Comment by itz-rj-here** [comment]
> Take help from AI Tools button

:)
My limit is over already. doing non useful things with gpt 🤣

**Comment by itz-rj-here** [comment]
> image
> How about this lol

🗿 what the 🗿

**Pull request closed without merging**
