### PR TITLE
Changed Bookmark Icon

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Description
- Changed Bookmark Icon
- Added Translatable tooltip

## Preview
image
image

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
@prem-k-r please review, I'll make any changes if required in the morning as my parent's scolding me today to sleep 😢

**Comment by prem-k-r** [comment]
Ok nw, Good night :)

**Comment by prem-k-r** [comment]
let's wait for others, I'm getting errors

**Comment by prem-k-r** [comment]
Functionality wise, it is working fine

**Comment by Thunder-Blaze** [comment]
Any more changes you would like ?

**Comment by XengShi** [comment]
> Any more changes you would like ?

image
Screenshot From 2024-12-26 09-07-39

Almost perfect, but if google apps is not enabled it should take that place instead of extra `margin right`

**Comment by XengShi** [comment]
Why icons is not aligned center as I can see your icons and there is no extra text like "Other bookmars" which is looking clean. 

image

**Comment by Thunder-Blaze** [comment]
> > Any more changes you would like ?
> 
> image Screenshot From 2024-12-26 09-07-39
> 
> Almost perfect, but if google apps is not enabled it should take that place instead of extra `margin right`

Sure, I'll fix that in a min, right now was working on the languages page (so many classlist toggles ☠️ - converted to single one 🙂)

And the icons are bit inward to show that they are inside a folder, if you want I can remove the padding for first folder groups

**Pull request merged**
