### PR TITLE
V3 rewrite

### PR DESCRIPTION
**Pull request by Minuga-RC**

### CODE REVIEW

**Comment by Minuga-RC** [comment]
@XengShi merge please

**Comment by itz-rj-here** [comment]
> @XengShi merge please

Bruh it has conflicts

**Comment by Minuga-RC** [comment]
How tho there is no files in the branch to even have conflicts lol

**Comment by XengShi** [comment]
You know better than me 🙃

**Comment by Minuga-RC** [comment]
> You know better than me 🙃

Idk man maybe download my repo and copy all the files to this your self 🤷‍♂️

**Comment by XengShi** [comment]
Okay, But I thing branch name v3 is confusing can I rename it like

Node-version or similar,

since we will be keep updating normal version

**Comment by Minuga-RC** [comment]
> Okay, But I think branch name v3 is confusing can I rename it like
> 
> Node-version or similar,
> 
> since we will be keep updating normal version 

I mean we can make the node version the main after it gets stable I mean it is already stable I will make a readme about setting it up for developers but users can install it from the release we make

**Comment by Minuga-RC** [comment]
> It could be because of .DS_Store
> @Minuga-RC you can try downloading it from v3 branch, then upload it in ur rewrite branch. It may solve conflict. 
> After merge, delete back .DS_Store

Alr I will try that

**Comment by Minuga-RC** [comment]
image
the thing is I cant even click on resolve conflicts

**Comment by Minuga-RC** [comment]
@XengShi just add these files to the repo and push it to v3 branch 
https://github.com/Minuga-RC/BetterMaterialYouNewTab/tree/v3-rewrite

**Comment by Minuga-RC** [comment]
wait a min I added the readme and that has conflicts right so if I delete both readme and index and there will be no conflicts??
image

**Comment by ZiClaud** [comment]
Screenshot from 2024-10-23 17-52-33
You're trying to commit the directory `node_modules`, which makes it look like you changed 3000 files and added 500,000 lines of code.

**Comment by Minuga-RC** [comment]
Lol I didn't mean to commit that lol

**Comment by ZiClaud** [comment]
> wait a min I added the readme and that has conflicts right so if I delete both readme and index and there will be no conflicts??

To fix the conflicts, I suggest you create a pull request from the branch [XengShi:v3](https://github.com/XengShi/materialYouNewTab/tree/v3) to [Minuga-RC:v3-rewrite](https://github.com/Minuga-RC/BetterMaterialYouNewTab/tree/v3-rewrite), fix the conflicts, and they should be resolved here too.

**Comment by Minuga-RC** [comment]
> > wait a min I added the readme and that has conflicts right so if I delete both readme and index and there will be no conflicts??
> 
> To fix the conflicts, I suggest you create a pull request from the branch [XengShi:v3](https://github.com/XengShi/materialYouNewTab/tree/v3) to [Minuga-RC:v3-rewrite](https://github.com/Minuga-RC/BetterMaterialYouNewTab/tree/v3-rewrite), fix the conflicts, and they should be resolved here too.

Isn't it what I have done here rn?

**Comment by prem12321kumar** [comment]
@Minuga-RC 
If the Resolve conflicts button is deactivated, your pull request's merge conflict is too complex to resolve on GitHub. You must resolve the merge conflict using an alternative Git client, or by using Git on the command line. For more information see "Resolving a merge conflict using the command line."
Source: GitHub Docs

**Comment by Minuga-RC** [comment]
> @Minuga-RC If the Resolve conflicts button is deactivated, your pull request's merge conflict is too complex to resolve on GitHub. You must resolve the merge conflict using an alternative Git client, or by using Git on the command line. For more information see "Resolving a merge conflict using the command line." Source: GitHub Docs

oh ty i will do that tmr

**Comment by Minuga-RC** [comment]
@XengShi fixed u can merge now

**Comment by Minuga-RC** [comment]
@XengShi all done here you should be able to merge now

**Comment by Minuga-RC** [comment]
@XengShi

**Comment by XengShi** [comment]
There are some inconsistencies in the UI and fonts, and it doesn’t load icons when offline. I suggest downloading all the icons so users still have a good experience if they open it offline.
I appreciate the work; the button effects and animations are awesome!

Screenshot 2024-10-28 221017
Screenshot 2024-10-28 221038

**Pull request merged**
