### PR TITLE
Transliteration for search engines and some others

### LINKED ISSUE #190: Transliteration for search engines
Screenshot from 2024-11-18 11-14-33
Screenshot from 2024-11-18 11-10-24

How about implementing transliteration for search engines in the selected language?

@itz-rj-here , @prem-k-r  Could you please also coordinate with the language translator to include translations for the search engines as well?

### PR DESCRIPTION
**Pull request by prem-k-r**
Closes #190

### CODE REVIEW

**Comment by itz-rj-here** [comment]
It doesn't even say duck duck go
image
?

**Comment by XengShi** [comment]
> It doesn't even say duck duck go
> image
> ?

I did that knowingly.. :⁠-⁠)

**Comment by XengShi** [comment]
> > It doesn't even say duck duck go
> > image
> > ?
> 
> I did that knowingly.. :⁠-⁠)
> We are also using different logo

**Review by itz-rj-here — APPROVED** [review]
All Good with the Bangla Language. :)

**Comment by itz-rj-here** [comment]
> > > It doesn't even say duck duck go
> > > image
> > > ?
> > 
> > 
> > I did that knowingly.. :⁠-⁠)
> > We are also using different logo

:)

**Comment by itz-rj-here** [comment]
There is a svg logo on the web 
image
so why selecting that?

**Comment by XengShi** [comment]
> There is a svg logo on the web 
> image
> so why selecting that?

What made you think that I couldn't find that logo anywhere so that's why I'm using that logo? 🙃 

Sometimes we don't need to follow all the rules, when we are making something for ourselves (not for any brand or companies or some formal things) we can still call it twitter and Duck for duckduckgo

**Comment by itz-rj-here** [comment]
> > There is a svg logo on the web
> > image
> > so why selecting that?
> 
> What made you think that I couldn't find that logo anywhere so that's why I'm using that logo? 🙃
> 
> Sometimes we don't need to follow all the rules, when we are making something for ourselves (not for any brand or companies or some formal things) we can still call it twitter and Duck for duckduckgo

I understand your words :)

**Comment by XengShi** [comment]
> I don't understand. Name is portugese and flag is brazil how?

Portugese is the most spoken language of Brazil I guess...

**Comment by itz-rj-here** [comment]
> > I don't understand. Name is portugese and flag is brazil how?
> 
> Portugese is the most spoken language of Brazil I guess...

How? Is that even possible?

**Comment by prem-k-r** [comment]
> > I don't understand. Name is portugese and flag is brazil how?
> 
> Portugese is the most spoken language of Brazil I guess...

yes,
"pt-pt" stands for Portuguese of Portugal and  "pt-br" stands for portuguese of Brazil.

**Comment by itz-rj-here** [comment]
> > > I don't understand. Name is portugese and flag is brazil how?
> > 
> > 
> > Portugese is the most spoken language of Brazil I guess...
> 
> yes, "pt-pt" stands for Portuguese of Portugal and "pt-br" stands for portuguese of Brazil.

Wow really impresive :)

**Comment by prem-k-r** [comment]
Done, change code to zh-CN, pt-BR, es-ES and corrected bn

**Comment by XengShi** [comment]
Screenshot from 2024-11-20 11-46-15

After selecting Russian language i am getting ugly scrollbar at bottom @prem-k-r

**Comment by prem-k-r** [comment]
Oh, it was not happening with me.. This should be because of width of translated Google Apps in Russian, I think. 
Just a sec

**Comment by prem-k-r** [comment]
Following is not translated into Czech, could you please do it at your convenience, @ceskyDJ 
```
"googleAppsMenuText": "Google Apps",
"googleAppsMenuInfo": "Show shortcut for Google Apps",
```

**Pull request merged**
