### PR TITLE
Fix Dark theme input bgcolor and shadow in date/greeting and Usertext

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by prem-k-r** [comment]
@XengShi

**Review by itz-rj-here — APPROVED** [review]

**Comment by XengShi** [comment]
After after commenting those line
Rest of the themes are still working fine.

So please figure it out if those codes are unwanted

**Comment by prem-k-r** [comment]
> But after commenting those line Rest of the themes are still working fine.
> 
> So please figure it out if those codes are unwanted

they are currently being used for grey theme
fix: #252

**Comment by prem-k-r** [comment]
Reverted some changes to avoid conflicts with #256 
Also added shadow in Date/greetings and Usertext

**Pull request merged**
