### PR TITLE
fixed color glitches in FireFox

### LINKED ISSUE #308: [Bug] Colour glitches on start since last update
https://github.com/user-attachments/assets/ca5b7884-319d-43d3-b119-48fadbc4cc1a

It only happens when I have the page open

https://github.com/user-attachments/assets/2683677c-d0e2-433b-8f68-b894ed49c51f

It also happens with other colours

### PR DESCRIPTION
**Pull request by giwih**
## Related Issues
- Issue Closes #308

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Review by ZiClaud — APPROVED** [review]
It works, thank you!

**Review by itz-rj-here — APPROVED** [review]
@prem-k-r please review it 
I guess it’s ok

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
> ## Related Issues
> * Issue [[Bug] Colour glitches on start since last update #308](https://github.com/XengShi/materialYouNewTab/issues/308)

Github trick: You can write as `Closes #308` in PR description, it will automatically closes the issue when the PR is merged :)

**Comment by XengShi** [comment]
This change will disable live changes of colors in Chrome.  I think live updates provide a better user experience. Therefore, I am merging this change into the Firefox-specific branch.

https://github.com/user-attachments/assets/ff2d1c56-5ed6-4a5b-8e63-92ce56290d1a

**Comment by ZiClaud** [comment]
I'd like for this to be reopened and changed the code to:
```js
// Function to detect if the browser is Firefox
function isFirefox() {
    return navigator.userAgent.toLowerCase().includes('firefox');
}

// Apply appropriate listeners based on the browser
if (isFirefox()) {
    // Add listeners for Firefox
    colorPicker.removeEventListener('change', handleColorPickerChange);
    colorPicker.addEventListener('change', handleColorPickerChange);
} else {
    // Add listeners for Chrome and Safari
    colorPicker.removeEventListener('input', handleColorPickerChange);
    colorPicker.addEventListener('input', handleColorPickerChange);
}
```
And remove the Firefox-specific branch

I've tested it on both Firefox and Chrome, and it works.
Didn't test it on Safari, Brave and others.

Also, to make the code more solid, create a folder: `browserUtils.js` and put in there
```js
// browserUtils.js

/**
 * Detect if the browser is Firefox.
 * @returns {boolean} True if the browser is Firefox.
 */
export function isFirefox() {
    return navigator.userAgent.toLowerCase().includes('firefox');
}

/**
 * Detect if the browser is Chrome.
 * @returns {boolean} True if the browser is Chrome.
 */
export function isChrome() {
    return navigator.userAgent.toLowerCase().includes('chrome') &&
           !navigator.userAgent.toLowerCase().includes('edge') &&
           !navigator.userAgent.toLowerCase().includes('opera');
}
```

@XengShi @giwih @prem-k-r

**Comment by prem-k-r** [comment]
isfirefox is already defined, no need for browserUtils.js

we can go for directly
image


there has been an extra option added for firefox #323 , so not a good idea to delete the branch

**Pull request closed without merging**
