### PR TITLE
Changed bookmark grid bg circles color and made minor adjustments

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
image
to
image

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by XengShi** [comment]
image
The arrow button for bookmarks is not looking appropriate can you make it something like this.

**Comment by prem-k-r** [comment]
yeah agree, 
but for wider screen that position might looks bad.
image

**Comment by prem-k-r** [comment]
css.. it will take much time for me.. 

@Thunder-Blaze bro, any idea

**Comment by Thunder-Blaze** [comment]
Should I change the arrow to Bookmarks button ?

**Comment by XengShi** [comment]
> Should I change the arrow to Bookmarks button ?



Yess, you can use icons like this

**Comment by prem-k-r** [comment]
> image The arrow button for bookmarks is not looking appropriate can you make it something like this.

it this better?
image
with a smaller size

**Comment by Thunder-Blaze** [comment]
sure, I'll try but It'll take some time, I wanna clear my fork and then create a new one (I've made to many mistakes | biggest of them I committed in main branch)

So once API pr get merged, I'll make it

btw how are u guys making the designs ? I'm assuming you are not making changes in website, are you ?

**Comment by prem-k-r** [comment]
please check above if above ok, else lets switch to bookmarks logo before g apps

**Comment by prem-k-r** [comment]
> Should I change the arrow to Bookmarks button ?

ohk the bookmark icon.. 
https://icon-sets.iconify.design/?query=bookmark

**Comment by Thunder-Blaze** [comment]
oh I found the way, no need to delete the fork anymore before making changes
@XengShi lmk when you decide what to do

**Comment by prem-k-r** [comment]
> sure, I'll try but It'll take some time, I wanna clear my fork and then create a new one (I've made to many mistakes | biggest of them I committed in main branch)
> 
> So once API pr get merged, I'll make it
> 
> btw how are u guys making the designs ? I'm assuming you are not making changes in website, are you ?

For text I use designmode, no hassle..
for ui change,, either edit image or tweak css

**Comment by prem-k-r** [comment]
I used to think searchbar is vertically centred but it is not lol

**Comment by prem-k-r** [comment]
> > btw how are u guys making the designs ? I'm assuming you are not making changes in website, are you ?
> 
> For text I use designmode, no hassle.. for ui change,, either edit image or tweak css

do you have any suggestion or anything that helps with this and want to share?

**Comment by Thunder-Blaze** [comment]
Nah, lol I didn't even knew about designmode
I usually photoshop which takes so much time on my i3

And you guys were sending new designs very quick, so I was curious

**Comment by prem-k-r** [comment]
designmode is fun to use, I guess you have googled out
just enter `document.designMode="on"` in console, and now you can edit texts
an alternative is adding contenteditable in html header like `<html contenteditable>`

**Comment by Thunder-Blaze** [comment]
Yeah googled and then tried it myself XD

Deleted a whole page using backspace lol

**Comment by XengShi** [comment]
image
Bookmarks are not working. @Thunder-Blaze @prem-k-r
Everything is messed up now.

**Comment by prem-k-r** [comment]
> image Bookmarks are not working. @Thunder-Blaze @prem-k-r Everything is messed up now.

Firefox?

**Comment by Thunder-Blaze** [comment]
looks like chrome

I think it's reading browser.bookmarks.contains
but since browser.bookmarks is undefined for chrome
it results in error

I think somehow the ternary is giving opposite results lol

also the ternery don't check if the browser is not both chrome or browser

**Comment by Thunder-Blaze** [comment]
wait its working for me in both chrome and firefox (main branch)
which branch are you on ?

**Comment by prem-k-r** [comment]
> wait its working for me in both chrome and firefox (main branch) which branch are you on ?

able to reproduce this after giwih's change, in chrome, opened as live server

**Comment by Thunder-Blaze** [comment]
ofc it won't work in live server as it needs bookmark accessing permissions
load it as extension

**Comment by prem-k-r** [comment]
> ## Description
> image to image



@XengShi, changed bg circles color from darkcolor to bgcolor.. can you please tell if this is better, or should I revert it?

**Comment by XengShi** [comment]
Yeah, This is better

**Comment by Thunder-Blaze** [comment]
image
I think this is looking bad ?
should I go with black instead for the dark mode ?

**Comment by prem-k-r** [comment]
yeah, maybe black and dark grey shades

**Comment by prem-k-r** [comment]
fixed conflicts and done some minor changes

**Comment by Thunder-Blaze** [comment]
image
how about this ?

**Comment by prem-k-r** [comment]
go with anything that looks good to you

**Comment by Thunder-Blaze** [comment]
image
light mode

**Review by itz-rj-here — APPROVED** [review]

**Review by itz-rj-here — APPROVED** [review]

**Pull request merged**
