### PR TITLE
Fix: Ensure Uploaded Background Image Persists After Refresh

### PR DESCRIPTION
**Pull request by prem-k-r**

### CODE REVIEW

**Comment by prem-k-r** [comment]
@XengShi working fine, 
couldn't verify in firefox if it work after exiting browser

**Comment by itz-rj-here** [comment]
image

Hehe :)

**Comment by itz-rj-here** [comment]
image

I guess it works fine :)

**Comment by itz-rj-here** [comment]
@XengShi You can merge this on the repo. It's perfectly working.

**Comment by XengShi** [comment]
> @XengShi You can merge this on the repo. It's perfectly working.

Will be merged after I test it....

**Comment by itz-rj-here** [comment]
> > @XengShi You can merge this on the repo. It's perfectly working.
> 
> Will be merged after I test it....

Ok np.

**Comment by itz-rj-here** [comment]
> > @XengShi You can merge this on the repo. It's perfectly working.
> 
> Will be merged after I test it....

Don't forget to see my changes too. :)

**Pull request merged**
