### PR TITLE
Updated Screenshots in README.md

### PR DESCRIPTION
**Pull request by prem-k-r**
changed/added more screenshots
Added 2, replaced 2
image
image
image
image

### CODE REVIEW

**Comment by MestreWalla** [comment]
Someone had asked me for a screenshot running in safari, but I can't find the conversation anymore.

**Comment by MestreWalla** [comment]
Someone had asked me for a screenshot running in safari, but I can't find the conversation anymore.

**Comment by itz-rj-here** [comment]
> 
> 
> Someone had asked me for a screenshot running in safari, but I can't find the conversation anymore.

I wanted the screenshot of the installation process in the ss. Let me show you.

**Comment by itz-rj-here** [comment]
Can you get this for the safari thingy.

**Comment by prem-k-r** [comment]
Will close this PR later, do use the screenshots if needed
@XengShi

**Pull request closed without merging**
