### PR TITLE
Fix/bookmark toggle

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
Works as a temproary fix
Later will add another state variable to keep the state of grid as grid

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
don't merge yet

**Comment by Thunder-Blaze** [comment]
@prem-k-r can you check quick
I think this will fix

**Review by prem-k-r — APPROVED** [review]

**Comment by prem-k-r** [comment]
all good now

**Comment by prem-k-r** [comment]
@XengShi

**Comment by prem-k-r** [comment]
> @XengShi

Included this one and submitted at store?

**Pull request merged**
