### PR TITLE
Resolved some warnings for Unsafe assignment to innerHTML

### PR DESCRIPTION
**Pull request by prem-k-r**
## Description
Resolved some warnings for Unsafe assignment to innerHTML in Weather stuff

and 
image

## Checklist
- [x] I have read and followed the [Contributing Guidelines](../CONTRIBUTING.md).
- [x] I have added necessary tests.
- [x] The project builds and runs without issues.

### CODE REVIEW

**Comment by prem-k-r** [comment]
todo: function swapDropdown(selectedElement)

**Comment by prem-k-r** [comment]
image

**Comment by prem-k-r** [comment]
@XengShi Fix 6 warnings (hopes so),
rest I don't fully understand the impact and consequence so I am not touching them

**Comment by prem-k-r** [comment]
> image

@princevora can you please check `function swapDropdown(selectedElement)`

**Comment by princevora** [comment]
> > image
> 
> @princevora can you please check `function swapDropdown(selectedElement)`

What happened bro, i am unable to view image

**Comment by prem-k-r** [comment]
> @princevora can you please check `function swapDropdown(selectedElement)`

`Unsafe assignment to innerHTML` warning

**Pull request merged**
